/* tslint:disable */
/**
 * API documentation
 * To use this api you need an access token. To getList the token, send a post request with your email address to api-users resource and one will be send to your. See below for information on how to use this api and if you have any questions you can contact us at helpdesk@laji.fi.  Place refer to [schema.laji.fi](http://schema.laji.fi/) for more information about the used vocabulary
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: TEST This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import { PagedResult } from '../model/PagedResult';
import { Collection } from '../model/Collection';
import { environment } from '../../../environments/environment';
import 'rxjs/add/operator/map';
import { HttpClient } from '@angular/common/http';
import { Util } from '../service/util.service';

@Injectable()
export class CollectionApi {
  protected basePath = environment.apiBase;

  constructor(protected http: HttpClient) {
  }

  /**
   * Get all collections
   *
   * @param lang Language of fields that have multiple languages. Return english if asked language not found. If multi is selected fields will contain language objects
   * @param idIn Include only items with there ids. Multiple values are separated by a comma (,)
   * @param page Page number
   * @param pageSize Page size
   */
  public findAll(lang?: string, idIn?: string, page?: string, pageSize?: string, extraHttpRequestParams?: any): Observable<PagedResult<Collection>> {
    const path = this.basePath + '/collections';

    const queryParameters = {...Util.removeFromObject(extraHttpRequestParams)};
    if (lang !== undefined) {
      queryParameters['lang'] = lang;
    }

    if (idIn !== undefined) {
      queryParameters['idIn'] = idIn;
    }

    if (page !== undefined) {
      queryParameters['page'] = page;
    }

    if (pageSize !== undefined) {
      queryParameters['pageSize'] = pageSize;
    }

    return this.http.get<PagedResult<Collection>>(path, {params: queryParameters});
  }

  /**
   * Find collection by id
   *
   * @param id
   * @param lang Language of fields that have multiple languages. Return english if asked language not found. If multi is selected fields will contain language objects
   */
  public findById(id: string, lang?: string, extraHttpRequestParams?: any): Observable<Collection> {
    const path = this.basePath + '/collections/{id}'
        .replace('{' + 'id' + '}', String(id));

    const queryParameters = {...Util.removeFromObject(extraHttpRequestParams)};
    // verify required parameter 'id' is not null or undefined
    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling collectionFindBySubject.');
    }
    if (lang !== undefined) {
      queryParameters['lang'] = lang;
    }

    return this.http.get<Collection>(path, {params: queryParameters});
  }

  /**
   * Get all collections belonging to the given id
   *
   * @param id
   * @param lang Language of fields that have multiple languages. Return english if asked language not found. If multi is selected fields will contain language objects
   * @param page Page number
   * @param pageSize Page size
   */
  public findChildren(id: string, lang?: string, page?: string, pageSize?: string, extraHttpRequestParams?: any): Observable<PagedResult<Collection>> {
    const path = this.basePath + '/collections/{id}/children'
        .replace('{' + 'id' + '}', String(id));

    const queryParameters = {...Util.removeFromObject(extraHttpRequestParams)};

    // verify required parameter 'id' is not null or undefined
    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling collectionFindChildren.');
    }
    if (lang !== undefined) {
      queryParameters['lang'] = lang;
    }

    if (page !== undefined) {
      queryParameters['page'] = page;
    }

    if (pageSize !== undefined) {
      queryParameters['pageSize'] = pageSize;
    }

    return this.http.get<PagedResult<Collection>>(path, {params: queryParameters});
  }

  /**
   * Get all root collections
   *
   * @param lang Language of fields that have multiple languages. Return english if asked language not found. If multi is selected fields will contain language objects
   * @param page Page number
   * @param pageSize Page size
   */
  public findRoots(lang?: string, page?: string, pageSize?: string, extraHttpRequestParams?: any): Observable<PagedResult<Collection>> {
    const path = this.basePath + '/collections/roots';

    const queryParameters = {...Util.removeFromObject(extraHttpRequestParams)};

    if (lang !== undefined) {
      queryParameters['lang'] = lang;
    }

    if (page !== undefined) {
      queryParameters['page'] = page;
    }

    if (pageSize !== undefined) {
      queryParameters['pageSize'] = pageSize;
    }

    return this.http.get<PagedResult<Collection>>(path, {params: queryParameters});
  }

}
