/* tslint:disable */
/**
 * API documentation
 * To use this api you need an access token. To getList the token, send a post request with your email address to api-users resource and one will be send to your. See below for information on how to use this api and if you have any questions you can contact us at helpdesk@laji.fi.  Place refer to [schema.laji.fi](http://schema.laji.fi/) for more information about the used vocabulary
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: TEST This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import { PagedResult } from '../model/PagedResult';
import { HttpClient, HttpResponse } from '@angular/common/http';
import { Util } from '../service/util.service';
import { Document } from '../model/Document';
import { environment } from '../../../environments/environment';

'use strict';

@Injectable({providedIn: 'root'})
export class DocumentApi {
  protected basePath = environment.apiBase;

  constructor(protected http: HttpClient) {
  }

  /**
   * Create a new document and persist it
   *
   * @param data Model instance data
   * @param userToken User authentication token
   */
  public create(data: Document, userToken: string, extraHttpRequestParams?: any): Observable<Document> {
    const path = this.basePath + '/documents';

    const queryParameters = {...Util.removeUndefinedFromObject(extraHttpRequestParams)};
    // verify required parameter 'data' is not null or undefined
    if (data === null || data === undefined) {
      throw new Error('Required parameter data was null or undefined when calling documentCreateWithUser.');
    }
    // verify required parameter 'personToken' is not null or undefined
    if (userToken === null || userToken === undefined) {
      throw new Error('Required parameter personToken was null or undefined when calling documentCreateWithUser.');
    }
    if (userToken !== undefined) {
      queryParameters['personToken'] = userToken;
    }

    return this.http.post<Document>(path, data, {params: queryParameters});
  }

  /**
   * Find a document with id
   *
   * @param id Find document with the id
   * @param userToken User authentication token
   */
  public findById(id: string, userToken: string, extraHttpRequestParams?: any): Observable<Document> {
    const path = this.basePath + '/documents/{id}'
        .replace('{' + 'id' + '}', String(id));

    const queryParameters = {...Util.removeUndefinedFromObject(extraHttpRequestParams)};
    // verify required parameter 'id' is not null or undefined
    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling documentFindByIdWithUser.');
    }
    // verify required parameter 'personToken' is not null or undefined
    if (userToken === null || userToken === undefined) {
      throw new Error('Required parameter personToken was null or undefined when calling documentFindByIdWithUser.');
    }
    if (userToken !== undefined) {
      queryParameters['personToken'] = userToken;
    }

    return this.http.get<Document>(path, {params: queryParameters});
  }

  /**
   * Get all documents
   *
   * @param userToken User authentication token
   * @param page Page number
   * @param pageSize Page size
   */
  public findAll(userToken: string, page?: string, pageSize?: string, observationYear?: string, extraHttpRequestParams?: any): Observable<PagedResult<Document>> {
    const path = this.basePath + '/documents';

    const queryParameters = {...Util.removeUndefinedFromObject(extraHttpRequestParams)};
    // verify required parameter 'personToken' is not null or undefined
    if (userToken === null || userToken === undefined) {
      throw new Error('Required parameter personToken was null or undefined when calling documentFindWithUser.');
    }
    if (page !== undefined) {
      queryParameters['page'] = page;
    }

    if (pageSize !== undefined) {
      queryParameters['pageSize'] = pageSize;
    }

    if (userToken !== undefined) {
      queryParameters['personToken'] = userToken;
    }

    if (observationYear !== undefined) {
      queryParameters['observationYear'] = observationYear;
    }

    return this.http.get<PagedResult<Document>>(path, {params: queryParameters});
  }

  /**
   * Update existing document
   *
   * @param id Id for the document
   * @param data Model instance data
   * @param userToken User authentication token
   */
  public update(id: string, data: Document, userToken: string, extraHttpRequestParams?: any): Observable<Document> {
    const path = this.basePath + '/documents/{id}'
        .replace('{' + 'id' + '}', String(id));

    const queryParameters = {...Util.removeUndefinedFromObject(extraHttpRequestParams)};
    // verify required parameter 'id' is not null or undefined
    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling documentUpdateWithUser.');
    }
    // verify required parameter 'data' is not null or undefined
    if (data === null || data === undefined) {
      throw new Error('Required parameter data was null or undefined when calling documentUpdateWithUser.');
    }
    // verify required parameter 'personToken' is not null or undefined
    if (userToken === null || userToken === undefined) {
      throw new Error('Required parameter personToken was null or undefined when calling documentUpdateWithUser.');
    }
    if (userToken !== undefined) {
      queryParameters['personToken'] = userToken;
    }

    return this.http.put<Document>(path, data, {params: queryParameters});
  }

  /**
   *
   * @param userToken User authentication token
   */
  public countByYear(userToken: string, extraHttpRequestParams?: any): Observable<any> {
    const path = this.basePath + '/documents/count/byYear';

    const queryParameters = {...Util.removeUndefinedFromObject(extraHttpRequestParams)};

    // verify required parameter 'personToken' is not null or undefined
    if (userToken === null || userToken === undefined) {
      throw new Error('Required parameter personToken was null or undefined when calling documentFindByYearWithUser.');
    }
    if (userToken !== undefined) {
      queryParameters['personToken'] = userToken;
    }

    return this.http.get(path, {params: queryParameters});
  }

  public validate(data: Document, extraHttpRequestParams?: any ): Observable<any> {
    const path = this.basePath + `/documents/validate`;

    const queryParameters = {...Util.removeUndefinedFromObject(extraHttpRequestParams)};

    return this.http.post(path, data, {params: queryParameters, observe: 'response'})
      .map((response: HttpResponse<any>) => {
        if (response.status === 204) {
          return undefined;
        } else {
          return response.body;
        }
      });
  }

  public delete(id: string, personToken: string, extraHttpRequestParams?: any ): Observable<any> {
    const path = this.basePath + `/documents/${id}`;

    const queryParameters = {...Util.removeUndefinedFromObject(extraHttpRequestParams)};
    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling documentUpdateWithUser.');
    }
    if (personToken === null || personToken === undefined) {
      throw new Error('Required parameter personToken was null.');
    }
    queryParameters['personToken'] = personToken;


    return this.http.delete(path, {params: queryParameters});
  }
}
