/**
 * API documentation
 * To use this api you need an access token. To get the token, send a post request with your email address to api-users resource and one will be send to your. See below for information on how to use this api and if you have any questions you can contact us at helpdesk@laji.fi.  Place refer to [schema.laji.fi](http://schema.laji.fi/) for more information about the used vocabulary
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: TEST This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Http, Headers, RequestOptionsArgs, Response, URLSearchParams} from '@angular/http';
import {Injectable, Optional} from '@angular/core';
import {Observable} from 'rxjs/Observable';
import * as models from '../model';
import 'rxjs/Rx';

/* tslint:disable:no-unused-variable member-ordering */

'use strict';
import {PagedResult} from "../model/PagedResult";

@Injectable()
export class MetadataApi {
    protected basePath = '/api';
    public defaultHeaders : Headers = new Headers();

    constructor(protected http: Http, @Optional() basePath: string) {
        if (basePath) {
            this.basePath = basePath;
        }
    }

    /**
     * Returns info about all the classes
     *
     * @param lang
     */
    public metadataAllClasses (lang?: string, extraHttpRequestParams?: any ) : Observable<PagedResult<Array<models.Metadata>>> {
        const path = this.basePath + '/metadata/classes';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        if (lang !== undefined) {
            queryParameters.set('lang', lang);
        }

        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Returns info about all the properties
     *
     * @param lang
     */
    public metadataAllProperties (lang?: string, extraHttpRequestParams?: any ) : Observable<PagedResult<Array<models.Property>>> {
        const path = this.basePath + '/metadata/properties';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        if (lang !== undefined) {
            queryParameters.set('lang', lang);
        }

        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Returns all ranges that are of select (alt) type
     *
     * @param lang
     * @param asLookupObject return select values as key value object instead of a list
     */
    public metadataFindAllRanges (lang?: string, asLookupObject?: boolean, extraHttpRequestParams?: any ) : Observable<any> {
        const path = this.basePath + '/metadata/ranges';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        if (lang !== undefined) {
            queryParameters.set('lang', lang);
        }

        if (asLookupObject !== undefined) {
            queryParameters.set('asLookupObject', asLookupObject ? 'true' : 'false');
        }

        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Returns info about the class
     *
     * @param _class
     * @param lang
     */
    public metadataFindClass (_class: string, lang?: string, extraHttpRequestParams?: any ) : Observable<models.Metadata> {
        const path = this.basePath + '/metadata/classes/{class}'
            .replace('{' + 'class' + '}', String(_class));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter '_class' is not null or undefined
        if (_class === null || _class === undefined) {
            throw new Error('Required parameter _class was null or undefined when calling metadataFindClass.');
        }
        if (lang !== undefined) {
            queryParameters.set('lang', lang);
        }

        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Returns info all classes properties
     *
     * @param _class
     * @param lang
     */
    public metadataFindClassProperties (_class: string, lang?: string, extraHttpRequestParams?: any ) : Observable<Array<models.Metadata>> {
        const path = this.basePath + '/metadata/classes/{class}/properties'
            .replace('{' + 'class' + '}', String(_class));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter '_class' is not null or undefined
        if (_class === null || _class === undefined) {
            throw new Error('Required parameter _class was null or undefined when calling metadataFindClassProperties.');
        }
        if (lang !== undefined) {
            queryParameters.set('lang', lang);
        }

        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Returns classes properties with key values of ranges used that are of select (alt) type
     *
     * @param _class
     * @param lang
     * @param asLookupObject return select values as key value object instead of a list
     */
    public metadataFindClassRanges (_class: string, lang?: string, asLookupObject?: boolean, extraHttpRequestParams?: any ) : Observable<any> {
        const path = this.basePath + '/metadata/classes/{class}/ranges'
            .replace('{' + 'class' + '}', String(_class));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter '_class' is not null or undefined
        if (_class === null || _class === undefined) {
            throw new Error('Required parameter _class was null or undefined when calling metadataFindClassRanges.');
        }
        if (lang !== undefined) {
            queryParameters.set('lang', lang);
        }

        if (asLookupObject !== undefined) {
            queryParameters.set('asLookupObject', asLookupObject ? 'true' : 'false');
        }

        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Returns key value list of properties range that are of select (alt) type
     *
     * @param property
     * @param lang
     * @param asLookupObject return select values as key value object instead of a list
     */
    public metadataFindPropertiesRanges (property: string, lang?: string, asLookupObject?: boolean, extraHttpRequestParams?: any ) : Observable<any> {
        const path = this.basePath + '/metadata/properties/{property}/ranges'
            .replace('{' + 'property' + '}', String(property));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'property' is not null or undefined
        if (property === null || property === undefined) {
            throw new Error('Required parameter property was null or undefined when calling metadataFindPropertiesRanges.');
        }
        if (lang !== undefined) {
            queryParameters.set('lang', lang);
        }

        if (asLookupObject !== undefined) {
            queryParameters.set('asLookupObject', asLookupObject ? 'true' : 'false');
        }

        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Returns info about all the properties
     *
     * @param property
     * @param lang
     */
    public metadataFindProperty (property: string, lang?: string, extraHttpRequestParams?: any ) : Observable<models.Property> {
        const path = this.basePath + '/metadata/properties/{property}'
            .replace('{' + 'property' + '}', String(property));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'property' is not null or undefined
        if (property === null || property === undefined) {
            throw new Error('Required parameter property was null or undefined when calling metadataFindProperty.');
        }
        if (lang !== undefined) {
            queryParameters.set('lang', lang);
        }

        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Returns range that is of type select (alt)
     *
     * @param range
     * @param lang
     * @param asLookupObject return select values as key value object instead of a list
     */
    public metadataFindRange (range: string, lang?: string, asLookupObject?: boolean, extraHttpRequestParams?: any ) : Observable<any> {
        const path = this.basePath + '/metadata/ranges/{range}'
            .replace('{' + 'range' + '}', String(range));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'range' is not null or undefined
        if (range === null || range === undefined) {
            throw new Error('Required parameter range was null or undefined when calling metadataFindRange.');
        }
        if (lang !== undefined) {
            queryParameters.set('lang', lang);
        }

        if (asLookupObject !== undefined) {
            queryParameters.set('asLookupObject', asLookupObject ? 'true' : 'false');
        }

        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

}
