/* tslint:disable */
/**
 * API documentation
 * To use this api you need an access token. To getList the token, send a post request with your email address to api-users resource and one will be send to your. See below for information on how to use this api and if you have any questions you can contact us at helpdesk@laji.fi.  Place refer to [schema.laji.fi](http://schema.laji.fi/) for more information about the used vocabulary
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: TEST This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import { PagedResult } from '../model/PagedResult';
import { HttpClient } from '@angular/common/http';
import { Util } from '../service/util.service';
import { RedListTaxonGroup } from '../model/RedListTaxonGroup';
import { environment } from '../../../environments/environment';


'use strict';

@Injectable({providedIn: 'root'})
export class RedListTaxonGroupApi {
  protected basePath = environment.apiBase;

  constructor(protected http: HttpClient) {
  }

  /**
   * Get all InformalTaxonGroups
   *
   * @param lang Language of fields that have multiple languages. Return english if asked language not found. If multi is selected fields will contain language objects
   * @param page Page number
   * @param pageSize Page size
   */
  public redListTaxonGroupsFind(lang?: string, page?: string, pageSize?: string, extraHttpRequestParams?: any): Observable<PagedResult<RedListTaxonGroup>> {
    const path = this.basePath + '/red-list-evaluation-groups';

    const queryParameters = {...Util.removeUndefinedFromObject(extraHttpRequestParams)};
    if (lang !== undefined) {
      queryParameters['lang'] = lang;
    }

    if (page !== undefined) {
      queryParameters['page'] = page;
    }

    if (pageSize !== undefined) {
      queryParameters['pageSize'] = pageSize;
    }

    return this.http.get<PagedResult<RedListTaxonGroup>>(path, {params: queryParameters});
  }

  /**
   * Find InformalTaxonGroup by id
   *
   * @param id
   * @param lang Language of fields that have multiple languages. Return english if asked language not found. If multi is selected fields will contain language objects
   */
  public redListTaxonGroupsFindById(id: string, lang?: string, extraHttpRequestParams?: any): Observable<RedListTaxonGroup> {
    const path = this.basePath + '/red-list-evaluation-groups/{id}'
        .replace('{' + 'id' + '}', String(id));

    const queryParameters = {...Util.removeUndefinedFromObject(extraHttpRequestParams)};
    // verify required parameter 'id' is not null or undefined
    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling redListTaxonGroupsFindById.');
    }
    if (lang !== undefined) {
      queryParameters['lang'] = lang;
    }

    return this.http.get<RedListTaxonGroup>(path, {params: queryParameters});
  }

  /**
   * Get root informal taxon groups
   *
   * @param lang Language of fields that have multiple languages. Return english if asked language not found.
   * @param page Page number
   * @param pageSize Page size
   */
  public redListTaxonGroupsFindRoots(lang?: string, page?: string, pageSize?: string, extraHttpRequestParams?: any): Observable<PagedResult<RedListTaxonGroup>> {
    const path = this.basePath + '/red-list-evaluation-groups/roots';

    const queryParameters = {...Util.removeUndefinedFromObject(extraHttpRequestParams)};
    if (lang !== undefined) {
      queryParameters['lang'] = lang;
    }

    if (page !== undefined) {
      queryParameters['page'] = page;
    }

    if (pageSize !== undefined) {
      queryParameters['pageSize'] = pageSize;
    }

    return this.http.get<PagedResult<RedListTaxonGroup>>(path, {params: queryParameters});
  }

  /**
   * Get immediate children of the informal group
   *
   * @param id
   * @param lang Language of fields that have multiple languages. Return english if asked language not found.
   * @param page Page number
   * @param pageSize Page size
   */
  public redListTaxonGroupsGetChildren(id: string, lang?: string, page?: string, pageSize?: string, extraHttpRequestParams?: any): Observable<PagedResult<RedListTaxonGroup>> {
    const path = this.basePath + '/red-list-evaluation-groups/{id}/children'
        .replace('{' + 'id' + '}', String(id));

    const queryParameters = {...Util.removeUndefinedFromObject(extraHttpRequestParams)};
    // verify required parameter 'id' is not null or undefined
    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling redListTaxonGroupsGetChildren.');
    }
    if (lang !== undefined) {
      queryParameters['lang'] = lang;
    }

    if (page !== undefined) {
      queryParameters['page'] = page;
    }

    if (pageSize !== undefined) {
      queryParameters['pageSize'] = pageSize;
    }

    return this.http.get<PagedResult<RedListTaxonGroup>>(path, {params: queryParameters});
  }

  /**
   * Get parents for a informal group
   *
   * @param id
   * @param lang Language of fields that have multiple languages. Return english if asked language not found.
   */
  public redListTaxonGroupsGetParents(id: string, lang?: string, extraHttpRequestParams?: any): Observable<Array<RedListTaxonGroup>> {
    const path = this.basePath + '/red-list-evaluation-groups/{id}/parents'
        .replace('{' + 'id' + '}', String(id));

    const queryParameters = {...Util.removeUndefinedFromObject(extraHttpRequestParams)};
    // verify required parameter 'id' is not null or undefined
    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling redListTaxonGroupsGetChildren.');
    }
    if (lang !== undefined) {
      queryParameters['lang'] = lang;
    }

    return this.http.get<RedListTaxonGroup[]>(path, {params: queryParameters});
  }

  /**
   * Get current groups parents and parents siblings
   *
   * @param id
   * @param lang Language of fields that have multiple languages. Return english if asked language not found.
   * @param page Page number
   * @param pageSize Page size
   */
  public redListTaxonGroupsGetParentLevel(id: string, lang?: string, page?: string, pageSize?: string, extraHttpRequestParams?: any): Observable<PagedResult<Array<RedListTaxonGroup>>> {
    const path = this.basePath + '/red-list-evaluation-groups/{id}/parentLevel'
        .replace('{' + 'id' + '}', String(id));

    const queryParameters = {...Util.removeUndefinedFromObject(extraHttpRequestParams)};
    // verify required parameter 'id' is not null or undefined
    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling redListTaxonGroupsGetParentLevel.');
    }
    if (lang !== undefined) {
      queryParameters['lang'] = lang;
    }

    if (page !== undefined) {
      queryParameters['page'] = page;
    }

    if (pageSize !== undefined) {
      queryParameters['pageSize'] = pageSize;
    }

    return this.http.get<PagedResult<Array<RedListTaxonGroup>>>(path, {params: queryParameters});
  }

  /**
   * Get full tree of informal groups with hasSubGroup extended
   *
   * @param lang Language of fields that have multiple languages. Return english if asked language not found.
   * @param page Page number
   * @param pageSize Page size
   */
  public redListTaxonGroupsGetTree(lang?: string, page?: string, pageSize?: string, extraHttpRequestParams?: any): Observable<PagedResult<RedListTaxonGroup>> {
    const path = this.basePath + '/red-list-evaluation-groups/tree';

    const queryParameters = {...Util.removeUndefinedFromObject(extraHttpRequestParams)};
    if (lang !== undefined) {
      queryParameters['lang'] = lang;
    }

    if (page !== undefined) {
      queryParameters['page'] = page;
    }

    if (pageSize !== undefined) {
      queryParameters['pageSize'] = pageSize;
    }

    return this.http.get<PagedResult<RedListTaxonGroup>>(path, {params: queryParameters});
  }

  /**
   * Get current groups with it&#39;s siblings
   *
   * @param id
   * @param lang Language of fields that have multiple languages. Return english if asked language not found.
   * @param page Page number
   * @param pageSize Page size
   */
  public redListTaxonGroupsGetWithSiblings(id: string, lang?: string, page?: string, pageSize?: string, extraHttpRequestParams?: any): Observable<PagedResult<RedListTaxonGroup>> {
    const path = this.basePath + '/red-list-evaluation-groups/{id}/siblings'
        .replace('{' + 'id' + '}', String(id));

    const queryParameters = {...Util.removeUndefinedFromObject(extraHttpRequestParams)};
    // verify required parameter 'id' is not null or undefined
    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling redListTaxonGroupsGetWithSiblings.');
    }
    if (lang !== undefined) {
      queryParameters['lang'] = lang;
    }

    if (page !== undefined) {
      queryParameters['page'] = page;
    }

    if (pageSize !== undefined) {
      queryParameters['pageSize'] = pageSize;
    }

    return this.http.get<PagedResult<RedListTaxonGroup>>(path, {params: queryParameters});
  }

}
