/**
 * API documentation
 * To use this api you need an access token. To get the token, send a post request with your email address to api-users resource and one will be send to your. See below for information on how to use this api and if you have any questions you can contact us at helpdesk@laji.fi.  Place refer to [schema.laji.fi](http://schema.laji.fi/) for more information about the used vocabulary
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: TEST This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Http, Headers, RequestOptionsArgs, Response, URLSearchParams} from '@angular/http';
import {Injectable, Optional} from '@angular/core';
import {Observable} from 'rxjs/Observable';
import {WarehouseQueryInterface, PagedResult} from '../model';
import 'rxjs/Rx';

/* tslint:disable:no-unused-variable member-ordering */

'use strict';

@Injectable()
export class WarehouseApi {
  protected basePath = '/api';
  public defaultHeaders:Headers = new Headers();

  constructor(protected http:Http, @Optional() basePath:string) {
    if (basePath) {
      this.basePath = basePath;
    }
  }

  /**
   * PLACEHOLDER - Not Yet implemented
   * Get loaded documents from your data source that have not been processed successfully. Requires that API key has load permissions.
   */
  public warehouseErrorsGet(extraHttpRequestParams?:any):Observable<string> {
    const path = this.basePath + '/warehouse/errors';

    let queryParameters = new URLSearchParams();
    let headerParams = this.defaultHeaders;
    let requestOptions:RequestOptionsArgs = {
      method: 'GET',
      headers: headerParams,
      search: queryParameters
    };

    return this.http.request(path, requestOptions)
      .map((response:Response) => {
        if (response.status === 204) {
          return undefined;
        } else {
          return response.json();
        }
      });
  }

  /**
   * Perform aggregation query using given filters and aggregation
   * Aggregates the results of the query based on given \&quot;aggregateBy\&quot; parameter or parameters. Returns count of units, individual count sum and maximum and min and max date.
   * @param query query to make to ware house
   * @param includeNonValidTaxons By default, query results include also entries where target name does not match taxonomy. To get only entries where one and only one taxon matches given target name, set this parameter to false.
   * @param aggregateBy Define fields to aggregate by. Multiple values are seperated by a comma (,) or by giving the HTTP parameter multiple times.
   * @param orderBy Define order of fields. Defaults to count of units (desc). Give number of the column, first is 1. aggregateBy -fields are first, followed by count of units, individual count sum and maximum and min and max date. Multiple values are seperated by a comma (,) or by giving the HTTP parameter multiple times.
   * @param pageSize Set number of results in one page.
   * @param page Set current page.
   */
  public warehousePrivateQueryAggregateGet(query:WarehouseQueryInterface, includeNonValidTaxons?:boolean, aggregateBy?:Array<string>, orderBy?:Array<string>, pageSize?:number, page?:number, extraHttpRequestParams?:any):Observable<string> {
    const path = this.basePath + '/warehouse/private-query/aggregate';

    let queryParameters = new URLSearchParams();
    let headerParams = this.defaultHeaders;

    this.addQueryToQueryParams(query, queryParameters);
    this.addMetaToQuery(queryParameters, includeNonValidTaxons, undefined, orderBy, pageSize, page);

    //headerParams.set('accept', accept);

    let requestOptions:RequestOptionsArgs = {
      method: 'GET',
      headers: headerParams,
      search: queryParameters
    };

    return this.http.request(path, requestOptions)
      .map((response:Response) => {
        if (response.status === 204) {
          return undefined;
        } else {
          return response.json();
        }
      });
  }

  /**
   * Get count of results using given filters
   * Use this API to test how many results your query would return and then proceed with list query. Also returns max result count allowed for list queries.
   * @param query query to make to ware house
   */
  public warehousePrivateQueryCountGet(query:WarehouseQueryInterface, extraHttpRequestParams?:any):Observable<string> {
    const path = this.basePath + '/warehouse/private-query/count';

    let queryParameters = new URLSearchParams();
    let headerParams = this.defaultHeaders;

    this.addQueryToQueryParams(query, queryParameters);


    // headerParams.set('accept', accept);

    let requestOptions:RequestOptionsArgs = {
      method: 'GET',
      headers: headerParams,
      search: queryParameters
    };

    return this.http.request(path, requestOptions)
      .map((response:Response) => {
        if (response.status === 204) {
          return undefined;
        } else {
          return response.json();
        }
      });
  }

  /**
   * Get list of results using given filters
   * Get list of results. Maximum number of results is 10000. Before making a list query, you should check with /count how many results the query yields. Application/json and application/xml responses respect the \&quot;selected\&quot; parameter, but application/dwc+xml does not support all fields.
   * @param query query to make to ware house
   * @param includeNonValidTaxons By default, query results include also entries where target name does not match taxonomy. To get only entries where one and only one taxon matches given target name, set this parameter to false.
   * @param selected Define what fields to include to the result. Defaults to [document.documentId, gathering.gatheringId, unit.unitId, document.sourceId, document.collectionId, document.namedPlaceId, document.secureLevel, document.secureReason, document.keywords, gathering.team, gathering.eventDate.begin, gathering.eventDate.end, gathering.timeBegin, gathering.timeEnd, gathering.higherGeography, gathering.country, gathering.province, gathering.municipality, gathering.locality, gathering.conversions.wgs84CenterPoint.lat, gathering.conversions.wgs84CenterPoint.lon, gathering.interpretations.coordinateAccuracy, gathering.interpretations.sourceOfCoordinates, unit.linkings.taxon.qname, unit.linkings.taxon.species, unit.linkings.taxon.scientificName, unit.linkings.taxon.vernacularName, unit.taxonVerbatim, unit.abundanceString, unit.recordBasis, unit.mediaCount, unit.notes] Multiple values are seperated by a comma (,) or by giving the HTTP parameter multiple times.
   * @param orderBy Define what fields to use when sorting results. If using default select, defaults to [gathering.eventDate.begin DESC, document.loadDate DESC, unit.taxonVerbatim ASC]. If using custom select there is no default order. Each fieldname given as parameter defaults to ASC - if you want to sort using descending order, add \&quot; DESC\&quot; to the end of the field name. Multiple values are seperated by a comma (,) or by giving the HTTP parameter multiple times.
   * @param pageSize Set number of results in one page.
   * @param page Set current page.
   */
  public warehousePrivateQueryListGet(query:WarehouseQueryInterface, includeNonValidTaxons?:boolean, selected?:Array<string>, orderBy?:Array<string>, pageSize?:number, page?:number, extraHttpRequestParams?:any):Observable<string> {
    const path = this.basePath + '/warehouse/private-query/list';

    let queryParameters = new URLSearchParams();
    let headerParams = this.defaultHeaders;

    this.addQueryToQueryParams(query, queryParameters);
    this.addMetaToQuery(queryParameters, includeNonValidTaxons, undefined, orderBy, pageSize, page);


    //    headerParams.set('accept', accept);

    let requestOptions:RequestOptionsArgs = {
      method: 'GET',
      headers: headerParams,
      search: queryParameters
    };

    return this.http.request(path, requestOptions)
      .map((response:Response) => {
        if (response.status === 204) {
          return undefined;
        } else {
          return response.json();
        }
      });
  }

  /**
   * Get single full document.
   * Get single full document by document URI. Contains the document, gatherings and units, including facts, media etc
   * @param documentId Full document ID (URI identifier)
   */
  public warehousePrivateQuerySingleGet(documentId:string, extraHttpRequestParams?:any):Observable<string> {
    const path = this.basePath + '/warehouse/private-query/single';

    let queryParameters = new URLSearchParams();
    let headerParams = this.defaultHeaders;
    // verify required parameter 'documentId' is not null or undefined
    if (documentId === null || documentId === undefined) {
      throw new Error('Required parameter documentId was null or undefined when calling warehousePrivateQuerySingleGet.');
    }
    queryParameters.set('documentId', documentId);

    //  headerParams.set('accept', accept);

    let requestOptions:RequestOptionsArgs = {
      method: 'GET',
      headers: headerParams,
      search: queryParameters
    };

    return this.http.request(path, requestOptions)
      .map((response:Response) => {
        if (response.status === 204) {
          return undefined;
        } else {
          return response.json();
        }
      });
  }

  /**
   * Load data to the Data Warehouse
   * Requires that API key has load permissions. Data is given in request body. Supports multiple data formats. See [documentation](https://laji.fi/information/node/1234) (TODO) for complete reference. Accepts all payloads that pass format validation (for example is valid XML), but that does not mean the data will be processed succesfully. Use error-api to get feedback about processing failures.
   * @param documents See [documentation](https://laji.fi/information/node/1234) (TODO) for complete reference. Can contain multiple documents.
   */
  public warehousePushPost(documents:string, extraHttpRequestParams?:any):Observable<string> {
    const path = this.basePath + '/warehouse/push';

    let queryParameters = new URLSearchParams();
    let headerParams = this.defaultHeaders;
    // verify required parameter 'documents' is not null or undefined
    if (documents === null || documents === undefined) {
      throw new Error('Required parameter documents was null or undefined when calling warehousePushPost.');
    }
    let requestOptions:RequestOptionsArgs = {
      method: 'POST',
      headers: headerParams,
      search: queryParameters
    };
    requestOptions.body = JSON.stringify(documents);

    return this.http.request(path, requestOptions)
      .map((response:Response) => {
        if (response.status === 204) {
          return undefined;
        } else {
          return response.json();
        }
      })
      .cache();
  }

  /**
   * Perform aggregation query using given filters and aggregation
   * Aggregates the results of the query based on given \&quot;aggregateBy\&quot; parameter or parameters. Returns count of units, individual count sum and maximum and min and max date.
   * @param query to make to the warehouse
   * @param includeNonValidTaxons By default, query results include also entries where target name does not match taxonomy. To get only entries where one and only one taxon matches given target name, set this parameter to false.
   * @param aggregateBy Define fields to aggregate by. Multiple values are seperated by a comma (,) or by giving the HTTP parameter multiple times.
   * @param orderBy Define order of fields. Defaults to count of units (desc). Give number of the column, first is 1. aggregateBy -fields are first, followed by count of units, individual count sum and maximum and min and max date. Multiple values are seperated by a comma (,) or by giving the HTTP parameter multiple times.
   * @param pageSize Set number of results in one page.
   * @param page Set current page.
   */
  public warehouseQueryAggregateGet(query:WarehouseQueryInterface, includeNonValidTaxons?:boolean, aggregateBy?:Array<string>, orderBy?:Array<string>, pageSize?:number, page?:number, taxonId?:Array<string>, target?:Array<string>, informalTaxonGroupId?:Array<string>, administrativeStatusId?:Array<string>, redListStatusId?:Array<string>, finnish?:boolean, invasive?:boolean, countryId?:Array<string>, finnishMunicipalityId?:Array<string>, biogeographicalProvinceId?:Array<string>, area?:Array<string>, time?:Array<string>, dayOfYearBegin?:number, dayOfYearEnd?:number, keyword?:Array<string>, collectionId?:Array<string>, sourceId?:Array<string>, recordBasis?:Array<string>, lifeStage?:Array<string>, sex?:Array<string>, documentId?:Array<string>, unitId?:Array<string>, individualId?:Array<string>, individualCountMin?:number, individualCountMax?:number, loadedLaterThan?:Date, coordinates?:Array<string>, typeSpecimen?:boolean, hasDocumentMedia?:boolean, hasGatheringMedia?:boolean, hasUnittMedia?:boolean, hasMedia?:boolean, secureReason?:Array<string>, editorId?:Array<string>, extraHttpRequestParams?:any):Observable<string> {
    const path = this.basePath + '/warehouse/query/aggregate';

    let queryParameters = new URLSearchParams();
    let headerParams = this.defaultHeaders;

    this.addQueryToQueryParams(query, queryParameters);
    this.addMetaToQuery(queryParameters, includeNonValidTaxons, undefined, orderBy, pageSize, page);
    //  headerParams.set('accept', accept);

    let requestOptions:RequestOptionsArgs = {
      method: 'GET',
      headers: headerParams,
      search: queryParameters
    };

    return this.http.request(path, requestOptions)
      .map((response:Response) => {
        if (response.status === 204) {
          return undefined;
        } else {
          return response.json();
        }
      })
      .cache();
  }

  /**
   * Get count of results using given filters
   * Use this API to test how many results your query would return and then proceed with list query. Also returns max result count allowed for list queries.
   * @param query to make to the warehouse
   * @param includeNonValidTaxons By default, query results include also entries where target name does not match taxonomy. To get only entries where one and only one taxon matches given target name, set this parameter to false.
   */
  public warehouseQueryCountGet(query:WarehouseQueryInterface, includeNonValidTaxons?:boolean, extraHttpRequestParams?:any):Observable<string> {
    const path = this.basePath + '/warehouse/query/count';

    let queryParameters = new URLSearchParams();
    let headerParams = this.defaultHeaders;
    this.addQueryToQueryParams(query, queryParameters);
    this.addMetaToQuery(queryParameters, includeNonValidTaxons);


    // headerParams.set('accept', accept);

    let requestOptions:RequestOptionsArgs = {
      method: 'GET',
      headers: headerParams,
      search: queryParameters
    };

    return this.http.request(path, requestOptions)
      .map((response:Response) => {
        if (response.status === 204) {
          return undefined;
        } else {
          return response.json();
        }
      })
      .cache();
  }

  /**
   * Get list of results using given filters
   * Get list of results. Maximum number of results is 10000. Before making a list query, you should check with /count how many results the query yields. Application/json and application/xml responses respect the \&quot;selected\&quot; parameter, but application/dwc+xml does not support all fields.
   * @param query to make to the warehouse
   * @param includeNonValidTaxons By default, query results include also entries where target name does not match taxonomy. To get only entries where one and only one taxon matches given target name, set this parameter to false.
   * @param selected Define what fields to include to the result. Defaults to [document.documentId, gathering.gatheringId, unit.unitId, document.sourceId, document.collectionId, document.namedPlaceId, document.secureLevel, document.secureReason, document.keywords, gathering.team, gathering.eventDate.begin, gathering.eventDate.end, gathering.timeBegin, gathering.timeEnd, gathering.higherGeography, gathering.country, gathering.province, gathering.municipality, gathering.locality, gathering.conversions.wgs84CenterPoint.lat, gathering.conversions.wgs84CenterPoint.lon, gathering.interpretations.coordinateAccuracy, gathering.interpretations.sourceOfCoordinates, unit.linkings.taxon.qname, unit.linkings.taxon.species, unit.linkings.taxon.scientificName, unit.linkings.taxon.vernacularName, unit.taxonVerbatim, unit.abundanceString, unit.recordBasis, unit.mediaCount, unit.notes] Multiple values are seperated by a comma (,) or by giving the HTTP parameter multiple times.
   * @param orderBy Define what fields to use when sorting results. If using default select, defaults to [gathering.eventDate.begin DESC, document.loadDate DESC, unit.taxonVerbatim ASC]. If using custom select there is no default order. Each fieldname given as parameter defaults to ASC - if you want to sort using descending order, add \&quot; DESC\&quot; to the end of the field name. Multiple values are seperated by a comma (,) or by giving the HTTP parameter multiple times.
   * @param pageSize Set number of results in one page.
   * @param page Set current page.
   */
  public warehouseQueryListGet(query:WarehouseQueryInterface, includeNonValidTaxons?:boolean, selected?:Array<string>, orderBy?:Array<string>, pageSize?:number, page?:number, extraHttpRequestParams?:any):Observable<PagedResult<any>> {
    const path = this.basePath + '/warehouse/query/list';

    let queryParameters = new URLSearchParams();
    let headerParams = this.defaultHeaders;
    this.addQueryToQueryParams(query, queryParameters);
    this.addMetaToQuery(queryParameters, includeNonValidTaxons, selected, orderBy, pageSize, page);


    //   headerParams.set('accept', accept);

    let requestOptions:RequestOptionsArgs = {
      method: 'GET',
      headers: headerParams,
      search: queryParameters
    };

    return this.http.request(path, requestOptions)
      .map((response:Response) => {
        if (response.status === 204) {
          return undefined;
        } else {
          return response.json();
        }
      });
  }

  /**
   * Get single full document.
   * Get single full document by document URI. Contains the document, gatherings and units, including facts, media etc
   * @param documentId Full document ID (URI identifier)
   */
  public warehouseQuerySingleGet(documentId:string, extraHttpRequestParams?:any):Observable<string> {
    const path = this.basePath + '/warehouse/query/single';

    let queryParameters = new URLSearchParams();
    let headerParams = this.defaultHeaders;
    // verify required parameter 'documentId' is not null or undefined
    if (documentId === null || documentId === undefined) {
      throw new Error('Required parameter documentId was null or undefined when calling warehouseQuerySingleGet.');
    }

    queryParameters.set('documentId', documentId);

    // headerParams.set('accept', accept);

    let requestOptions:RequestOptionsArgs = {
      method: 'GET',
      headers: headerParams,
      search: queryParameters
    };

    return this.http.request(path, requestOptions)
      .map((response:Response) => {
        if (response.status === 204) {
          return undefined;
        } else {
          return response.json();
        }
      });
  }

  private addMetaToQuery(queryParameters:URLSearchParams, includeNonValidTaxons?:boolean, selected?:Array<string>, orderBy?:Array<string>, pageSize?:number, page?:number):void {
    if (includeNonValidTaxons !== undefined) {
      queryParameters.set('includeNonValidTaxons', includeNonValidTaxons ? 'true' : 'false');
    }

    if (selected !== undefined) {
      queryParameters.set('selected', selected.join(','));
    }

    if (orderBy !== undefined) {
      queryParameters.set('orderBy', orderBy.join(',m'));
    }

    if (pageSize !== undefined) {
      queryParameters.set('pageSize', String(pageSize));
    }

    if (page !== undefined) {
      queryParameters.set('page', String(page));
    }
  }

  private addQueryToQueryParams(query:WarehouseQueryInterface, queryParameters:URLSearchParams):void {
    if (query.taxonId !== undefined) {
      queryParameters.set('taxonId', query.taxonId.join(','));
    }

    if (query.target !== undefined) {
      queryParameters.set('target', query.target.join(','));
    }

    if (query.informalTaxonGroupId !== undefined) {
      queryParameters.set('informalTaxonGroupId', query.informalTaxonGroupId.join(','));
    }

    if (query.administrativeStatusId !== undefined) {
      queryParameters.set('administrativeStatusId', query.administrativeStatusId.join(','));
    }

    if (query.redListStatusId !== undefined) {
      queryParameters.set('redListStatusId', query.redListStatusId.join(','));
    }

    if (query.finnish !== undefined) {
      queryParameters.set('finnish', query.finnish ? 'true' : 'false');
    }

    if (query.invasive !== undefined) {
      queryParameters.set('invasive', query.invasive ? 'true' : 'false');
    }

    if (query.countryId !== undefined) {
      queryParameters.set('countryId', query.countryId.join(','));
    }

    if (query.finnishMunicipalityId !== undefined) {
      queryParameters.set('finnishMunicipalityId', query.finnishMunicipalityId.join(','));
    }

    if (query.biogeographicalProvinceId !== undefined) {
      queryParameters.set('biogeographicalProvinceId', query.biogeographicalProvinceId.join(','));
    }

    if (query.area !== undefined) {
      queryParameters.set('area', query.area.join(','));
    }

    if (query.time !== undefined) {
      queryParameters.set('time', query.time.join(','));
    }

    if (query.dayOfYearBegin !== undefined) {
      queryParameters.set('dayOfYearBegin', String(query.dayOfYearBegin));
    }

    if (query.dayOfYearEnd !== undefined) {
      queryParameters.set('dayOfYearEnd', String(query.dayOfYearEnd));
    }

    if (query.keyword !== undefined) {
      queryParameters.set('keyword', query.keyword.join(','));
    }

    if (query.collectionId !== undefined) {
      queryParameters.set('collectionId', query.collectionId.join(','));
    }

    if (query.sourceId !== undefined) {
      queryParameters.set('sourceId', query.sourceId.join(','));
    }

    if (query.recordBasis !== undefined) {
      queryParameters.set('recordBasis', query.recordBasis.join(','));
    }

    if (query.lifeStage !== undefined) {
      queryParameters.set('lifeStage', query.lifeStage.join(','));
    }

    if (query.sex !== undefined) {
      queryParameters.set('sex', query.sex.join(','));
    }

    if (query.documentId !== undefined) {
      queryParameters.set('documentId', query.documentId.join(','));
    }

    if (query.unitId !== undefined) {
      queryParameters.set('unitId', query.unitId.join(','));
    }

    if (query.individualId !== undefined) {
      queryParameters.set('individualId', query.individualId.join(','));
    }

    if (query.individualCountMin !== undefined) {
      queryParameters.set('individualCountMin', String(query.individualCountMin));
    }

    if (query.individualCountMax !== undefined) {
      queryParameters.set('individualCountMax', String(query.individualCountMax));
    }

    if (query.loadedLaterThan !== undefined) {
      //queryParameters.set('loadedLaterThan', query.loadedLaterThan);
    }

    if (query.coordinates !== undefined) {
      queryParameters.set('coordinates', query.coordinates.join(','));
    }

    if (query.typeSpecimen !== undefined) {
      queryParameters.set('typeSpecimen', String(query.typeSpecimen));
    }

    if (query.hasDocumentMedia !== undefined) {
      queryParameters.set('hasDocumentMedia', query.hasDocumentMedia ? 'true' : 'false');
    }

    if (query.hasGatheringMedia !== undefined) {
      queryParameters.set('hasGatheringMedia', query.hasGatheringMedia ? 'true' : 'false');
    }

    if (query.hasUnittMedia !== undefined) {
      queryParameters.set('hasUnittMedia', query.hasUnittMedia ? 'true' : 'false');
    }

    if (query.hasMedia !== undefined) {
      queryParameters.set('hasMedia', query.hasMedia ? 'true' : 'false');
    }

    if (query.secureReason !== undefined) {
      queryParameters.set('secureReason', query.secureReason.join(','));
    }

    if (query.editorId !== undefined) {
      queryParameters.set('editorId', query.editorId.join(','));
    }
  }

}
