version: '3.4'

services:
  front:
    container_name: laji
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
      - '4200:4200'
      - '49153:49153'
    environment:
      - NODE_ENV=dev
