version: '3'

services:
  redis:
    image: 'redis'
  front:
    volumes:
      - '.:/app:delegated'
      - '/app/node_modules'
    depends_on:
      - 'redis'
    environment:
      - REDIS_HOST=redis
    command: 'npm run start:ssr:local'
