version: '3'

services:
  front:
    container_name: laji
    build: .
    volumes:
      - '.:/app:delegated'
      - '/app/node_modules'
    ports:
      - '3000:3000'
      - '4200:4200'
      - '49153:49153'
    environment:
      - NODE_ENV=dev
    command: 'npm run start'
