/* tslint:disable */
/**
 * API documentation
 * To use this api you need an access token. To getList the token, send a post request with your email address to api-users resource and one will be send to your. See below for information on how to use this api and if you have any questions you can contact us at helpdesk@laji.fi.  Place refer to [schema.laji.fi](http://schema.laji.fi/) for more information about the used vocabulary
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 import { Injectable } from '@angular/core';
 import { Observable } from 'rxjs/Observable';
 import { Image } from '../model/Image';
 import { HttpClient } from '@angular/common/http';
 import { Util } from '../service/util.service';
 import { environment } from '../../../environments/environment';
 
 /* tslint:disable:no-unused-variable member-ordering */
 
 'use strict';
 
 @Injectable({providedIn: 'root'})
 export class ImageApi {
   protected basePath = environment.apiBase;
 
   constructor(protected http: HttpClient) {
   }
 
   /**
    * return image data with the given query
    *
    * @param id id of the image
    * @param lang lang of the image
    * 
    */
   public imageFindById(id: string, lang?: string, langFallback?: boolean, extraHttpRequestParams?: any): Observable<Image> {
     const path = this.basePath + '/images/{id}'
         .replace('{' + 'id' + '}', String(id));
 
     const queryParameters = {...Util.removeFromObject(extraHttpRequestParams)};
     // verify required parameter 'id' is not null or undefined
     if (id === null || id === undefined) {
       throw new Error('Required parameter id was null or undefined when calling imageFindById.');
     }
     if (lang !== undefined) {
       queryParameters['lang'] = lang;
     }
     if (langFallback !== undefined) {
        queryParameters['langFallback'] = langFallback ? 'true' : 'false';
      }
     return this.http.get<Image>(path, {params: queryParameters});
   }
 
 
 }
 