/* eslint-disable */
/**
 * API documentation
 * To use this api you need an access token. To getList the token, send a post request with your email address to api-users resource and one will be send to your. See below for information on how to use this api and if you have any questions you can contact us at helpdesk@laji.fi.  Place refer to [schema.laji.fi](http://schema.laji.fi/) for more information about the used vocabulary
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: TEST This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { PagedResult } from '../model/PagedResult';
import { ArrayResult } from '../model/ArrayResult';
import { LajiApiClientBService } from 'projects/laji-api-client-b/src/laji-api-client-b.service';
import { components } from 'projects/laji-api-client-b/generated/api.d';

export type InformalTaxonGroup = components['schemas']['store-informalTaxonGroup'];

@Injectable({providedIn: 'root'})
export class InformalTaxonGroupApi {
  constructor(
    private api: LajiApiClientBService
  ) { }

  /**
   * Get all InformalTaxonGroups
   * @param page Page number
   * @param pageSize Page size
   * @param idIn Array of ids to search by
   */
  public informalTaxonGroupFind(page?: number, pageSize?: number, idIn?: string[]): Observable<PagedResult<InformalTaxonGroup>> {
    return this.api.get('/informal-taxon-groups', { query: { idIn: idIn?.join(','), page, pageSize }});
  }

  /**
   * Find InformalTaxonGroup by id
   *
   * @param id
   */
  public informalTaxonGroupFindById(id: string): Observable<InformalTaxonGroup> {
    if (!id.length) {
      throw new Error('Required parameter id was empty when calling informalTaxonGroupFindById.');
    }
    return this.api.get('/informal-taxon-groups/{id}', { path: { id }});
  }

  /**
   * Get root informal taxon groups
   *
   * @param lang Language of fields that have multiple languages. Return english if asked language not found.
   * @param page Page number
   * @param pageSize Page size
   */
  public informalTaxonGroupFindRoots(): Observable<ArrayResult<InformalTaxonGroup>> {
    return this.api.get('/informal-taxon-groups/roots');
  }

  /**
   * Get immediate children of the informal group
   * @param id
   */
  public informalTaxonGroupGetChildren(id: string): Observable<ArrayResult<InformalTaxonGroup>> {
    return this.api.get('/informal-taxon-groups/{id}/children', { path: { id }});
  }

  /**
   * Get parent for a informal group
   *
   * @param id
   */
  public informalTaxonGroupGetParent(id: string): Observable<InformalTaxonGroup> {
    return this.api.get('/informal-taxon-groups/{id}/parent', { path: { id }});
  }

  /**
   * Get full tree of informal groups with hasSubGroup extended
   * @param page Page number
   * @param pageSize Page size
   */
  public informalTaxonGroupGetTree(): Observable<ArrayResult<InformalTaxonGroup>> {
    return this.api.get('/informal-taxon-groups/tree');
  }

  /**
   * Get current groups with it&#39;s siblings
   *
   * @param id
   * @param page Page number
   * @param pageSize Page size
   */
  public informalTaxonGroupGetWithSiblings(id: string): Observable<ArrayResult<InformalTaxonGroup>> {
    return this.api.get('/informal-taxon-groups/{id}/siblings', { path: { id }});
  }
}
