'use strict';

/* eslint-disable */
/**
 * API documentation
 * To use this api you need an access token. To getList the token, send a post request with your email address to api-users resource and one will be send to your. See below for information on how to use this api and if you have any questions you can contact us at helpdesk@laji.fi.  Place refer to [schema.laji.fi](http://schema.laji.fi/) for more information about the used vocabulary
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: TEST This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { PagedResult } from '../model/PagedResult';
import { LajiApiClientBService } from 'projects/laji-api-client-b/src/laji-api-client-b.service';
import { components } from 'projects/laji-api-client-b/generated/api.d';
import { ArrayResult } from '../model/ArrayResult';

type RedListTaxonGroup = components['schemas']['store-iucnRedListTaxonGroup'];

@Injectable({providedIn: 'root'})
export class RedListTaxonGroupApi {
  constructor(
    protected api: LajiApiClientBService
  ) {}

  /**
   * Get all InformalTaxonGroups
   * @param page Page number
   * @param pageSize Page size
   */
  public redListTaxonGroupsFind(page?: number, pageSize?: number, idIn?: string[]): Observable<PagedResult<RedListTaxonGroup>> {
    return this.api.get('/red-list-evaluation-groups', { query: { idIn: idIn?.join(','), page, pageSize }})
  }

  /**
   * Find InformalTaxonGroup by id
   * @param id
   */
  public redListTaxonGroupsFindById(id: string): Observable<RedListTaxonGroup> {
    return this.api.get('/red-list-evaluation-groups/{id}', { path: { id }});
  }

  /**
   * Get root informal taxon groups
   */
  public redListTaxonGroupsFindRoots(): Observable<ArrayResult<RedListTaxonGroup>> {
    return this.api.get('/red-list-evaluation-groups/roots');
  }

  /**
   * Get immediate children of the informal group
   * @param id
   */
  public redListTaxonGroupsGetChildren(id: string): Observable<ArrayResult<RedListTaxonGroup>> {
    return this.api.get('/red-list-evaluation-groups/{id}/children', { path: { id }})
  }

  /**
   * Get parents for a informal group
   * @param id
   */
  public redListTaxonGroupsGetParents(id: string): Observable<RedListTaxonGroup> {
    return this.api.get('/red-list-evaluation-groups/{id}/parent', { path: { id }});

  }

  /**
   * Get full tree of informal groups with hasSubGroup extended
   */
  public redListTaxonGroupsGetTree(): Observable<ArrayResult<RedListTaxonGroup>> {
    return this.api.get('/red-list-evaluation-groups/tree');
  }

  /**
   * Get current groups with it&#39;s siblings
   * @param id
   */
  public redListTaxonGroupsGetWithSiblings(id: string): Observable<ArrayResult<RedListTaxonGroup>> {
    // verify required parameter 'id' is not null or undefined
    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling redListTaxonGroupsGetWithSiblings.');
    }

    return this.api.get('/red-list-evaluation-groups/{id}/siblings', { path: { id }});
  }

}
