/**
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Annotation } from './Annotation';


export interface AnnotationTag {
    id: string;
    /**
     *  If lang parameter is \'multi\' this will be a lang object instead of a string or an array of strings!
     */
    description?: string;
    /**
     *  If lang parameter is \'multi\' this will be a lang object instead of a string or an array of strings!
     */
    name?: string;
    requiredRolesAdd?: Array<Annotation.AnnotationRoleEnum>;
    requiredRolesRemove?: Array<Annotation.AnnotationRoleEnum>;
}

