/**
 * API documentation
 * To use this api you need an access token.  To get the token, send a post request with your email address to api-users
 * resource and one will be send to your. Each endpoint bellow has more information on how to use this API.
 * If you have any questions you can contact us at helpdesk@laji.fi.
 * You can find more documentation here: [in Finnish](https://laji.fi/about/806), in English (todo).
 * Please refer to [schema.laji.fi](http://schema.laji.fi/) for information about the used vocabulary.
 *
 * OpenAPI spec version: 0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Annotation {
    /**
     * Unique ID for the object. This will be automatically generated.
     */
    id?: string;

    /**
     * QName for MA.person
     */
    annotationByPerson?: string;

    /**
     * QName for KE.informationSystem
     */
    annotationBySystem?: string;

    annotationClass?: Annotation.AnnotationClassEnum;

    /**
     * dateTime string using ISO8601 format
     */
    created?: string;

    invasiveControlEffectiveness?: Annotation.InvasiveControlEffectivenessEnum;

    notes?: string;

    /**
     * QName for MY.document
     */
    rootID?: string;

    /**
     * QName for MY.unit
     */
    targetID?: string;

    taxon?: string;

    type?: Annotation.TypeEnum;

}
export namespace Annotation {
    export enum AnnotationClassEnum {
        AnnotationClassReliable = <any> 'MAN.annotationClassReliable',
        AnnotationClassLikely = <any> 'MAN.annotationClassLikely',
        AnnotationClassNeutral = <any> 'MAN.annotationClassNeutral',
        AnnotationClassSuspicious = <any> 'MAN.annotationClassSuspicious',
        AnnotationClassUnreliable = <any> 'MAN.annotationClassUnreliable',
        AnnotationClassSpam = <any> 'MAN.annotationClassSpam'
    }
    export enum InvasiveControlEffectivenessEnum {
        InvasiveControlEffectivenessFull = <any> 'MY.invasiveControlEffectivenessFull',
        InvasiveControlEffectivenessPartial = <any> 'MY.invasiveControlEffectivenessPartial',
        InvasiveControlEffectivenessNone = <any> 'MY.invasiveControlEffectivenessNone',
        InvasiveControlEffectivenessNotFound = <any> 'MY.invasiveControlEffectivenessNotFound'
    }
    export enum TypeEnum {
        TypeTaxon = <any> 'MAN.typeTaxon',
        TypeInvasiveControlEffectiveness = <any> 'MAN.typeInvasiveControlEffectiveness',
        TypeComment = <any> 'MAN.typeComment',
        TypeAcknowledged = <any> 'MAN.typeAcknowledged'
    }
}
