/**
 * OpenAPI spec version: 0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface GatheringFact {
    aCAFLAonAlder?: number;

    aCAFLAonBirch?: number;

    aCAFLAonGround?: number;

    aCAFLAonPine?: number;

    aCAFLAonSpruce?: number;

    cARSPIonAlder?: number;

    cARSPIonBirch?: number;

    cARSPIonGround?: number;

    cARSPIonPine?: number;

    cARSPIonSpruce?: number;

    lOXIAonAlder?: number;

    lOXIAonBirch?: number;

    lOXIAonGround?: number;

    lOXIAonPine?: number;

    lOXIAonSpruce?: number;

    abundanceBOMGAR?: GatheringFact.AbundanceBOMGAREnum;

    abundancePINENU?: GatheringFact.AbundancePINENUEnum;

    abundanceTURPIL?: GatheringFact.AbundanceTURPILEnum;

    birdFeederCount?: number;

    birdFeederCountBiotopeA?: number;

    birdFeederCountBiotopeB?: number;

    birdFeederCountBiotopeC?: number;

    birdFeederCountBiotopeD?: number;

    birdFeederCountBiotopeE?: number;

    birdFeederCountBiotopeF?: number;

    birdFeederCountBiotopeG?: number;

    birdFeederCountBiotopeH?: number;

    cloudAndRain?: GatheringFact.CloudAndRainEnum;

    descriptionBiotopeF?: string;

    feedingStationCount?: number;

    feedingStationCountBiotopeA?: number;

    feedingStationCountBiotopeB?: number;

    feedingStationCountBiotopeC?: number;

    feedingStationCountBiotopeD?: number;

    feedingStationCountBiotopeE?: number;

    feedingStationCountBiotopeF?: number;

    feedingStationCountBiotopeG?: number;

    feedingStationCountBiotopeH?: number;

    iceCover?: GatheringFact.IceCoverEnum;

    meanTemperature?: number;

    observerCount?: number;

    /**
     * Non-negative integer
     */
    observerID?: number;

    pineConesAtCensus?: GatheringFact.PineConesAtCensusEnum;

    /**
     * Non-negative integer
     */
    routeID?: number;

    /**
     * Non-negative integer
     */
    routeLength?: number;

    /**
     * Non-negative integer
     */
    routeLengthBiotopeA?: number;

    /**
     * Non-negative integer
     */
    routeLengthBiotopeB?: number;

    /**
     * Non-negative integer
     */
    routeLengthBiotopeC?: number;

    /**
     * Non-negative integer
     */
    routeLengthBiotopeD?: number;

    /**
     * Non-negative integer
     */
    routeLengthBiotopeE?: number;

    /**
     * Non-negative integer
     */
    routeLengthBiotopeF?: number;

    /**
     * Non-negative integer
     */
    routeLengthBiotopeG?: number;

    /**
     * Non-negative integer
     */
    routeLengthBiotopeH?: number;

    routeLengthChange?: number;

    routeLengthChangeBiotopeA?: number;

    routeLengthChangeBiotopeB?: number;

    routeLengthChangeBiotopeC?: number;

    routeLengthChangeBiotopeD?: number;

    routeLengthChangeBiotopeE?: number;

    routeLengthChangeBiotopeF?: number;

    routeLengthChangeBiotopeG?: number;

    routeLengthChangeBiotopeH?: number;

    snowAndIceOnTrees?: GatheringFact.SnowAndIceOnTreesEnum;

    snowCover?: GatheringFact.SnowCoverEnum;

    sorbusBerriesAtCensus?: GatheringFact.SorbusBerriesAtCensusEnum;

    sorbusBerriesEarlyFall?: GatheringFact.SorbusBerriesEarlyFallEnum;

    spruceConesAtCensus?: GatheringFact.SpruceConesAtCensusEnum;

    typeOfSnowCover?: GatheringFact.TypeOfSnowCoverEnum;

    visibility?: GatheringFact.VisibilityEnum;

    waterbodies?: GatheringFact.WaterbodiesEnum;

    wayOfTravel?: GatheringFact.WayOfTravelEnum;

    wayOfTravelNotes?: string;

    wind?: GatheringFact.WindEnum;

}
export namespace GatheringFact {
    export enum AbundanceBOMGAREnum {
        SpeciesAbundanceEnum0 = <any> 'WBC.speciesAbundanceEnum0',
        SpeciesAbundanceEnum1 = <any> 'WBC.speciesAbundanceEnum1',
        SpeciesAbundanceEnum2 = <any> 'WBC.speciesAbundanceEnum2',
        SpeciesAbundanceEnum3 = <any> 'WBC.speciesAbundanceEnum3'
    }
    export enum AbundancePINENUEnum {
        SpeciesAbundanceEnum0 = <any> 'WBC.speciesAbundanceEnum0',
        SpeciesAbundanceEnum1 = <any> 'WBC.speciesAbundanceEnum1',
        SpeciesAbundanceEnum2 = <any> 'WBC.speciesAbundanceEnum2',
        SpeciesAbundanceEnum3 = <any> 'WBC.speciesAbundanceEnum3'
    }
    export enum AbundanceTURPILEnum {
        SpeciesAbundanceEnum0 = <any> 'WBC.speciesAbundanceEnum0',
        SpeciesAbundanceEnum1 = <any> 'WBC.speciesAbundanceEnum1',
        SpeciesAbundanceEnum2 = <any> 'WBC.speciesAbundanceEnum2',
        SpeciesAbundanceEnum3 = <any> 'WBC.speciesAbundanceEnum3'
    }
    export enum CloudAndRainEnum {
        CloudAndRainEnum0 = <any> 'WBC.cloudAndRainEnum0',
        CloudAndRainEnum1 = <any> 'WBC.cloudAndRainEnum1',
        CloudAndRainEnum2 = <any> 'WBC.cloudAndRainEnum2',
        CloudAndRainEnum3 = <any> 'WBC.cloudAndRainEnum3',
        CloudAndRainEnum4 = <any> 'WBC.cloudAndRainEnum4'
    }
    export enum IceCoverEnum {
        IceCoverEnum0 = <any> 'WBC.iceCoverEnum0',
        IceCoverEnum1 = <any> 'WBC.iceCoverEnum1',
        IceCoverEnum2 = <any> 'WBC.iceCoverEnum2',
        IceCoverEnum3 = <any> 'WBC.iceCoverEnum3',
        IceCoverEnum4 = <any> 'WBC.iceCoverEnum4'
    }
    export enum PineConesAtCensusEnum {
        BerriesAndConesEnum0 = <any> 'WBC.berriesAndConesEnum0',
        BerriesAndConesEnum1 = <any> 'WBC.berriesAndConesEnum1',
        BerriesAndConesEnum2 = <any> 'WBC.berriesAndConesEnum2',
        BerriesAndConesEnum3 = <any> 'WBC.berriesAndConesEnum3',
        BerriesAndConesEnum4 = <any> 'WBC.berriesAndConesEnum4',
        BerriesAndConesEnum5 = <any> 'WBC.berriesAndConesEnum5',
        BerriesAndConesEnum6 = <any> 'WBC.berriesAndConesEnum6'
    }
    export enum SnowAndIceOnTreesEnum {
        SnowAndIceOnTreesEnum0 = <any> 'WBC.snowAndIceOnTreesEnum0',
        SnowAndIceOnTreesEnum1 = <any> 'WBC.snowAndIceOnTreesEnum1',
        SnowAndIceOnTreesEnum2 = <any> 'WBC.snowAndIceOnTreesEnum2',
        SnowAndIceOnTreesEnum3 = <any> 'WBC.snowAndIceOnTreesEnum3'
    }
    export enum SnowCoverEnum {
        SnowCoverEnum0 = <any> 'WBC.snowCoverEnum0',
        SnowCoverEnum1 = <any> 'WBC.snowCoverEnum1',
        SnowCoverEnum2 = <any> 'WBC.snowCoverEnum2',
        SnowCoverEnum3 = <any> 'WBC.snowCoverEnum3',
        SnowCoverEnum4 = <any> 'WBC.snowCoverEnum4',
        SnowCoverEnum5 = <any> 'WBC.snowCoverEnum5',
        SnowCoverEnum6 = <any> 'WBC.snowCoverEnum6',
        SnowCoverEnum7 = <any> 'WBC.snowCoverEnum7',
        SnowCoverEnum8 = <any> 'WBC.snowCoverEnum8'
    }
    export enum SorbusBerriesAtCensusEnum {
        BerriesAndConesEnum0 = <any> 'WBC.berriesAndConesEnum0',
        BerriesAndConesEnum1 = <any> 'WBC.berriesAndConesEnum1',
        BerriesAndConesEnum2 = <any> 'WBC.berriesAndConesEnum2',
        BerriesAndConesEnum3 = <any> 'WBC.berriesAndConesEnum3',
        BerriesAndConesEnum4 = <any> 'WBC.berriesAndConesEnum4',
        BerriesAndConesEnum5 = <any> 'WBC.berriesAndConesEnum5',
        BerriesAndConesEnum6 = <any> 'WBC.berriesAndConesEnum6'
    }
    export enum SorbusBerriesEarlyFallEnum {
        BerriesAndConesEnum0 = <any> 'WBC.berriesAndConesEnum0',
        BerriesAndConesEnum1 = <any> 'WBC.berriesAndConesEnum1',
        BerriesAndConesEnum2 = <any> 'WBC.berriesAndConesEnum2',
        BerriesAndConesEnum3 = <any> 'WBC.berriesAndConesEnum3',
        BerriesAndConesEnum4 = <any> 'WBC.berriesAndConesEnum4',
        BerriesAndConesEnum5 = <any> 'WBC.berriesAndConesEnum5',
        BerriesAndConesEnum6 = <any> 'WBC.berriesAndConesEnum6'
    }
    export enum SpruceConesAtCensusEnum {
        BerriesAndConesEnum0 = <any> 'WBC.berriesAndConesEnum0',
        BerriesAndConesEnum1 = <any> 'WBC.berriesAndConesEnum1',
        BerriesAndConesEnum2 = <any> 'WBC.berriesAndConesEnum2',
        BerriesAndConesEnum3 = <any> 'WBC.berriesAndConesEnum3',
        BerriesAndConesEnum4 = <any> 'WBC.berriesAndConesEnum4',
        BerriesAndConesEnum5 = <any> 'WBC.berriesAndConesEnum5',
        BerriesAndConesEnum6 = <any> 'WBC.berriesAndConesEnum6'
    }
    export enum TypeOfSnowCoverEnum {
        TypeOfSnowCoverEnum0 = <any> 'WBC.typeOfSnowCoverEnum0',
        TypeOfSnowCoverEnum1 = <any> 'WBC.typeOfSnowCoverEnum1',
        TypeOfSnowCoverEnum2 = <any> 'WBC.typeOfSnowCoverEnum2'
    }
    export enum VisibilityEnum {
        VisibilityEnum0 = <any> 'WBC.visibilityEnum0',
        VisibilityEnum1 = <any> 'WBC.visibilityEnum1',
        VisibilityEnum2 = <any> 'WBC.visibilityEnum2',
        VisibilityEnum3 = <any> 'WBC.visibilityEnum3',
        VisibilityEnum4 = <any> 'WBC.visibilityEnum4'
    }
    export enum WaterbodiesEnum {
        WaterbodiesEnum0 = <any> 'WBC.waterbodiesEnum0',
        WaterbodiesEnum1 = <any> 'WBC.waterbodiesEnum1',
        WaterbodiesEnum2 = <any> 'WBC.waterbodiesEnum2',
        WaterbodiesEnum3 = <any> 'WBC.waterbodiesEnum3',
        WaterbodiesEnum4 = <any> 'WBC.waterbodiesEnum4',
        WaterbodiesEnum5 = <any> 'WBC.waterbodiesEnum5'
    }
    export enum WayOfTravelEnum {
        WayOfTravelEnum0 = <any> 'WBC.wayOfTravelEnum0',
        WayOfTravelEnum1 = <any> 'WBC.wayOfTravelEnum1',
        WayOfTravelEnum2 = <any> 'WBC.wayOfTravelEnum2'
    }
    export enum WindEnum {
        WindEnum0 = <any> 'WBC.windEnum0',
        WindEnum1 = <any> 'WBC.windEnum1',
        WindEnum2 = <any> 'WBC.windEnum2',
        WindEnum3 = <any> 'WBC.windEnum3',
        WindEnum4 = <any> 'WBC.windEnum4'
    }
}
