/**
 * OpenAPI spec version: 0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TaxonCensus {
    /**
     * QName for MX.taxon
     */
    censusTaxonID: string;

    taxonCensusType: TaxonCensus.TaxonCensusTypeEnum;

}
export namespace TaxonCensus {
    export enum TaxonCensusTypeEnum {
        TaxonCensusTypeCounted = <any> 'MY.taxonCensusTypeCounted',
        TaxonCensusTypeEstimated = <any> 'MY.taxonCensusTypeEstimated',
        TaxonCensusTypeNotCounted = <any> 'MY.taxonCensusTypeNotCounted',
        TaxonCensusTypeUHEXCounted = <any> 'MY.taxonCensusTypeUHEXCounted',
        TaxonCensusTypeUHEXNotCounted = <any> 'MY.taxonCensusTypeUHEXNotCounted'
    }
}
