/**
 * API documentation
 * To use this api you need an access token. To get the token, send a post request with your email address to api-users resource and one will be send to your. See below for information on how to use this api and if you have any questions you can contact us at helpdesk@laji.fi.  Place refer to [schema.laji.fi](http://schema.laji.fi/) for more information about the used vocabulary
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: TEST This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

'use strict';
import * as models from './index';

export interface Units {


    /**
     * Unique ID for the object. (if none given id will be auto generated during insert)
     */
    id?: string;

    /**
     * Diameter at breast height, in centimeters
     */
    dBH?: string;

    /**
     * Leave empty if no sample taken, or if the sample was recorded separately
     */
    dNASampleLocation?: string;

    abundanceString?: string;

    age?: string;

    ageNotes?: string;

    ankleInMillimeters?: Array<string>;

    beakInMillimeters?: Array<string>;

    causeOfDeath?: string;

    chemistry?: string;

    /**
     * Numeric or other description on the amount of individuals (or sprouts, fruiting bodies or such) in the specimen. Sexes and juveniles can be specified like so: 1m2f3j (=1 male, 2 females, 3 juveniles)
     */
    count?: string;

    decayStage?: string;

    genotype?: string;

    gonadInMillimeters?: Array<string>;

    growthMediumName?: string;

    growthOtherConditions?: string;

    growthTemperature?: string;

    /**
     * Array of identifications
     */
    identifications?: Array<models.Identifications>;

    individualCount?: number;

    informalNameString?: string;

    infrasubspecificSubdivision?: string;

    lengthInMillimeters?: Array<string>;

    lifeStage?: string;

    lifeStageDescription?: string;

    macroscopy?: string;

    measurement?: Array<string>;

    microscopy?: string;

    mutant?: string;

    /**
     * Free-text notes
     */
    notes?: string;

    /**
     * Abundance of the taxon in the field
     */
    populationAbundance?: string;

    preparations?: string;

    /**
     * PUBLIC: all data can be published; PROTECTED: exact locality is hidden; PRIVATE: most of the data is hidden. If blank means same as public
     */
    publicityRestrictions?: string;

    recordBasis?: string;

    recordParts?: Array<string>;

    ring?: string;

    sex?: string;

    sexNotes?: string;

    tailInMillimeters?: Array<string>;

    typeSpecimen?: Array<string>;

    /**
     * Array of typeSpecimens
     */
    typeSpecimens?: Array<models.TypeSpecimens>;

    weightInGrams?: Array<string>;

    wingInMillimeters?: Array<string>;
}
