/**
 * OpenAPI spec version: 0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './index';

export interface UnitGathering {

    coordinatesGridYKJ?: string;

    dateBegin?: string;

    dateEnd?: string;

    /**
     * Geological information about gathering
     */
    geometry?: models.Geometry;

    /**
     * Informal description of the habitat
     */
    habitatDescription?: string;

    habitatIUCN?: string;

    /**
     * Unique ID for the object. This will be automatically generated.
     */
    id?: string;

    substrate?: string;

    /**
     * QName for MX.taxon
     */
    substrateSpeciesID?: string;

}
