/* eslint-disable @typescript-eslint/quotes */
/* eslint-disable max-len */
/*
Generated file. Do not edit manually!
*/

export const filters = {
  id: { prop: "id", filterType: "string", defaultValue: null },
  subjectid: { prop: "subject.id", filterType: "string", defaultValue: null },
  subjecttype: {
    prop: "subject.type",
    filterType: "enum",
    defaultValue: null,
    range: ["TDF.typeIndividual", "TDF.typePopulationGroup", "TDF.typeTaxon"],
  },
  subjectbasisOfRecord: {
    prop: "subject.basisOfRecord",
    filterType: "enum",
    defaultValue: null,
    range: [
      "MY.recordBasisPreservedSpecimen",
      "MY.recordBasisHumanObservation",
      "MY.recordBasisHumanObservationSeen",
      "MY.recordBasisHumanObservationHeard",
      "MY.recordBasisHumanObservationHandled",
      "MY.recordBasisHumanObservationPhoto",
      "MY.recordBasisHumanObservationAudio",
      "MY.recordBasisHumanObservationVideo",
      "MY.recordBasisHumanObservationIndirect",
      "MY.recordBasisMachineObservation",
      "MY.recordBasisMachineObservationPhoto",
      "MY.recordBasisMachineObservationVideo",
      "MY.recordBasisMachineObservationAudio",
      "MY.recordBasisMachineObservationGeologger",
      "MY.recordBasisMachineObservationSatelliteTransmitter",
      "MY.recordBasisFossilSpecimen",
      "MY.recordBasisSubfossilSpecimen",
      "MY.recordBasisSubfossilSpecimenAmberInclusion",
      "MY.recordBasisMaterialSample",
      "MY.recordBasisMaterialSampleAir",
      "MY.recordBasisMaterialSampleSoil",
      "MY.recordBasisMaterialSampleWater",
      "MY.recordBasisMicrobialSpecimen",
      "MY.recordBasisLivingSpecimen",
      "MY.recordBasisLiterature",
    ],
  },
  subjectfinbifOccurrenceId: {
    prop: "subject.finbifOccurrenceId",
    filterType: "string",
    defaultValue: null,
  },
  subjectgbifOccurrenceId: {
    prop: "subject.gbifOccurrenceId",
    filterType: "string",
    defaultValue: null,
  },
  subjectotherOccurrenceId: {
    prop: "subject.otherOccurrenceId",
    filterType: "string",
    defaultValue: null,
  },
  subjectkingdom: {
    prop: "subject.kingdom",
    filterType: "string",
    defaultValue: null,
  },
  subjectscientificName: {
    prop: "subject.scientificName",
    filterType: "string",
    defaultValue: null,
  },
  subjectauthor: {
    prop: "subject.author",
    filterType: "string",
    defaultValue: null,
  },
  subjectfunctionalGroupName: {
    prop: "subject.functionalGroupName",
    filterType: "string",
    defaultValue: null,
  },
  subjectotherTaxonId: {
    prop: "subject.otherTaxonId",
    filterType: "string",
    defaultValue: null,
  },
  subjectsex: {
    prop: "subject.sex",
    filterType: "enum",
    defaultValue: null,
    range: [
      "MY.sexM",
      "MY.sexF",
      "MY.sexW",
      "MY.sexU",
      "MY.sexN",
      "MY.sexX",
      "MY.sexE",
      "MY.sexC",
    ],
  },
  subjectlifeStage: {
    prop: "subject.lifeStage",
    filterType: "enum",
    defaultValue: null,
    range: [
      "MY.lifeStageAdult",
      "MY.lifeStageNymph",
      "MY.lifeStageLarva",
      "MY.lifeStageEgg",
      "MY.lifeStagePupa",
      "MY.lifeStageJuvenile",
      "MY.lifeStageSubimago",
      "MY.lifeStageImmature",
      "MY.lifeStageFertile",
      "MY.lifeStageSterile",
      "MY.lifeStageTadpole",
      "MY.lifeStageEmbryo",
      "MY.lifeStageSubadult",
      "MY.lifeStageMature",
      "MY.lifeStagePullus",
      "MY.lifeStageHatchedEgg",
      "MY.lifeStageHatchedPupa",
      "MY.lifeStageGall",
      "MY.lifeStageMarks",
      "MY.lifeStageTriungulin",
    ],
  },
  subjectageYears: {
    prop: "subject.ageYears",
    filterType: "number",
    defaultValue: null,
  },
  subjectindividualCount: {
    prop: "subject.individualCount",
    filterType: "number",
    defaultValue: null,
  },
  subjectdateBegin: {
    prop: "subject.dateBegin",
    filterType: "string",
    defaultValue: null,
  },
  subjectdateEnd: {
    prop: "subject.dateEnd",
    filterType: "string",
    defaultValue: null,
  },
  subjectyearBegin: {
    prop: "subject.yearBegin",
    filterType: "number",
    defaultValue: null,
  },
  subjectyearEnd: {
    prop: "subject.yearEnd",
    filterType: "number",
    defaultValue: null,
  },
  subjectseasonBegin: {
    prop: "subject.seasonBegin",
    filterType: "number",
    defaultValue: null,
  },
  subjectseasonEnd: {
    prop: "subject.seasonEnd",
    filterType: "number",
    defaultValue: null,
  },
  subjectlat: { prop: "subject.lat", filterType: "number", defaultValue: null },
  subjectlon: { prop: "subject.lon", filterType: "number", defaultValue: null },
  subjectlatMin: {
    prop: "subject.latMin",
    filterType: "number",
    defaultValue: null,
  },
  subjectlatMax: {
    prop: "subject.latMax",
    filterType: "number",
    defaultValue: null,
  },
  subjectlonMin: {
    prop: "subject.lonMin",
    filterType: "number",
    defaultValue: null,
  },
  subjectlonMax: {
    prop: "subject.lonMax",
    filterType: "number",
    defaultValue: null,
  },
  subjectcoordinateAccuracy: {
    prop: "subject.coordinateAccuracy",
    filterType: "number",
    defaultValue: null,
  },
  subjectelevation: {
    prop: "subject.elevation",
    filterType: "number",
    defaultValue: null,
  },
  subjecthigherGeography: {
    prop: "subject.higherGeography",
    filterType: "string",
    defaultValue: null,
  },
  subjectcountry: {
    prop: "subject.country",
    filterType: "string",
    defaultValue: null,
  },
  subjectmunicipality: {
    prop: "subject.municipality",
    filterType: "string",
    defaultValue: null,
  },
  subjectlocality: {
    prop: "subject.locality",
    filterType: "string",
    defaultValue: null,
  },
  subjectlocationIdentifiers: {
    prop: "subject.locationIdentifiers",
    filterType: "string",
    defaultValue: null,
  },
  subjecthabitat: {
    prop: "subject.habitat",
    filterType: "string",
    defaultValue: null,
  },
  subjectoccurrenceRemarks: {
    prop: "subject.occurrenceRemarks",
    filterType: "string",
    defaultValue: null,
  },
  subjectmeasurementDeterminedBy: {
    prop: "subject.measurementDeterminedBy",
    filterType: "string",
    defaultValue: null,
  },
  subjectmeasurementDeterminedDate: {
    prop: "subject.measurementDeterminedDate",
    filterType: "string",
    defaultValue: null,
  },
  subjectcreated: {
    prop: "subject.created",
    filterType: "string",
    defaultValue: null,
  },
  subjectmodified: {
    prop: "subject.modified",
    filterType: "string",
    defaultValue: null,
  },
  year: { prop: "year", filterType: "number", defaultValue: null },
  month: { prop: "month", filterType: "number", defaultValue: null },
  day: { prop: "day", filterType: "number", defaultValue: null },
  eventDate: { prop: "eventDate", filterType: "string", defaultValue: null },
  geodeticDatum: {
    prop: "geodeticDatum",
    filterType: "string",
    defaultValue: null,
  },
  traitid: { prop: "trait.id", filterType: "string", defaultValue: null },
  traitdataEntryName: {
    prop: "trait.dataEntryName",
    filterType: "string",
    defaultValue: null,
  },
  traitname: { prop: "trait.name", filterType: "string", defaultValue: null },
  traitdescription: {
    prop: "trait.description",
    filterType: "string",
    defaultValue: null,
  },
  traitbaseUnit: {
    prop: "trait.baseUnit",
    filterType: "enum",
    defaultValue: null,
    range: [
      "TDF.umNM",
      "TDF.umUM",
      "TDF.umMM",
      "TDF.umCM",
      "TDF.umM",
      "TDF.umKM",
      "TDF.umG",
      "TDF.umKG",
      "TDF.umA",
      "TDF.umS",
      "TDF.umML",
      "TDF.umL",
      "TDF.umMOL",
      "TDF.umMMOL",
      "TDF.umUMOL",
      "TDF.umHZ",
      "TDF.umP",
      "TDF.umPPT",
      "TDF.umPPM",
      "TDF.umC",
      "TDF.umMM2",
      "TDF.umCM2",
      "TDF.umM2",
      "TDF.umARE",
      "TDF.umHA",
      "TDF.umKM2",
      "TDF.umMM3",
      "TDF.umCM3",
      "TDF.umM3",
      "TDF.umGMOL",
      "TDF.umMOLL",
      "TDF.umCM2H",
    ],
  },
  traitrange: {
    prop: "trait.range",
    filterType: "enum",
    defaultValue: null,
    range: [
      "xsd:string",
      "xsd:decimal",
      "xsd:integer",
      "xsd:positiveInteger",
      "xsd:nonNegativeInteger",
      "xsd:boolean",
      "MX.taxon",
    ],
  },
  traitreference: {
    prop: "trait.reference",
    filterType: "string",
    defaultValue: null,
  },
  traitidentifiers: {
    prop: "trait.identifiers",
    filterType: "array",
    defaultValue: null,
    elementType: { _tag: "string" },
  },
  traitGroupname: {
    prop: "traitGroup.name",
    filterType: "string",
    defaultValue: null,
  },
  statisticalMethod: {
    prop: "statisticalMethod",
    filterType: "enum",
    defaultValue: null,
    range: [
      "TDF.statisticalMethodMin",
      "TDF.statisticalMethodMax",
      "TDF.statisticalMethodAvg",
      "TDF.statisticalMethodMedian",
      "TDF.statisticalMethodSD",
      "TDF.statisticalMethodMode",
    ],
  },
  value: { prop: "value", filterType: "string", defaultValue: null },
  valueNumeric: {
    prop: "valueNumeric",
    filterType: "number",
    defaultValue: null,
  },
  unit: {
    prop: "unit",
    filterType: "enum",
    defaultValue: null,
    range: [
      "TDF.umNM",
      "TDF.umUM",
      "TDF.umMM",
      "TDF.umCM",
      "TDF.umM",
      "TDF.umKM",
      "TDF.umG",
      "TDF.umKG",
      "TDF.umA",
      "TDF.umS",
      "TDF.umML",
      "TDF.umL",
      "TDF.umMOL",
      "TDF.umMMOL",
      "TDF.umUMOL",
      "TDF.umHZ",
      "TDF.umP",
      "TDF.umPPT",
      "TDF.umPPM",
      "TDF.umC",
      "TDF.umMM2",
      "TDF.umCM2",
      "TDF.umM2",
      "TDF.umARE",
      "TDF.umHA",
      "TDF.umKM2",
      "TDF.umMM3",
      "TDF.umCM3",
      "TDF.umM3",
      "TDF.umGMOL",
      "TDF.umMOLL",
      "TDF.umCM2H",
    ],
  },
  measurementAccuracy: {
    prop: "measurementAccuracy",
    filterType: "number",
    defaultValue: null,
  },
  originalValue: {
    prop: "originalValue",
    filterType: "string",
    defaultValue: null,
  },
  originalValueNumeric: {
    prop: "originalValueNumeric",
    filterType: "number",
    defaultValue: null,
  },
  originalUnit: {
    prop: "originalUnit",
    filterType: "enum",
    defaultValue: null,
    range: [
      "TDF.umNM",
      "TDF.umUM",
      "TDF.umMM",
      "TDF.umCM",
      "TDF.umM",
      "TDF.umKM",
      "TDF.umG",
      "TDF.umKG",
      "TDF.umA",
      "TDF.umS",
      "TDF.umML",
      "TDF.umL",
      "TDF.umMOL",
      "TDF.umMMOL",
      "TDF.umUMOL",
      "TDF.umHZ",
      "TDF.umP",
      "TDF.umPPT",
      "TDF.umPPM",
      "TDF.umC",
      "TDF.umMM2",
      "TDF.umCM2",
      "TDF.umM2",
      "TDF.umARE",
      "TDF.umHA",
      "TDF.umKM2",
      "TDF.umMM3",
      "TDF.umCM3",
      "TDF.umM3",
      "TDF.umGMOL",
      "TDF.umMOLL",
      "TDF.umCM2H",
    ],
  },
  originalMeasurementAccuracy: {
    prop: "originalMeasurementAccuracy",
    filterType: "number",
    defaultValue: null,
  },
  subjectFinBIFTaxonid: {
    prop: "subjectFinBIFTaxon.id",
    filterType: "string",
    defaultValue: null,
  },
  subjectFinBIFTaxontaxonomicOrder: {
    prop: "subjectFinBIFTaxon.taxonomicOrder",
    filterType: "number",
    defaultValue: null,
  },
  subjectFinBIFTaxontaxonRank: {
    prop: "subjectFinBIFTaxon.taxonRank",
    filterType: "string",
    defaultValue: null,
  },
  subjectFinBIFTaxonscientificName: {
    prop: "subjectFinBIFTaxon.scientificName",
    filterType: "string",
    defaultValue: null,
  },
  subjectFinBIFTaxoncursiveName: {
    prop: "subjectFinBIFTaxon.cursiveName",
    filterType: "boolean",
    defaultValue: null,
  },
  subjectFinBIFTaxonauthor: {
    prop: "subjectFinBIFTaxon.author",
    filterType: "string",
    defaultValue: null,
  },
  subjectFinBIFTaxonhigherTaxadomain: {
    prop: "subjectFinBIFTaxon.higherTaxa.domain",
    filterType: "string",
    defaultValue: null,
  },
  subjectFinBIFTaxonhigherTaxakingdom: {
    prop: "subjectFinBIFTaxon.higherTaxa.kingdom",
    filterType: "string",
    defaultValue: null,
  },
  subjectFinBIFTaxonhigherTaxaphylum: {
    prop: "subjectFinBIFTaxon.higherTaxa.phylum",
    filterType: "string",
    defaultValue: null,
  },
  subjectFinBIFTaxonhigherTaxasubphylum: {
    prop: "subjectFinBIFTaxon.higherTaxa.subphylum",
    filterType: "string",
    defaultValue: null,
  },
  subjectFinBIFTaxonhigherTaxadivision: {
    prop: "subjectFinBIFTaxon.higherTaxa.division",
    filterType: "string",
    defaultValue: null,
  },
  subjectFinBIFTaxonhigherTaxaclass: {
    prop: "subjectFinBIFTaxon.higherTaxa.class",
    filterType: "string",
    defaultValue: null,
  },
  subjectFinBIFTaxonhigherTaxasubclass: {
    prop: "subjectFinBIFTaxon.higherTaxa.subclass",
    filterType: "string",
    defaultValue: null,
  },
  subjectFinBIFTaxonhigherTaxaorder: {
    prop: "subjectFinBIFTaxon.higherTaxa.order",
    filterType: "string",
    defaultValue: null,
  },
  subjectFinBIFTaxonhigherTaxasuborder: {
    prop: "subjectFinBIFTaxon.higherTaxa.suborder",
    filterType: "string",
    defaultValue: null,
  },
  subjectFinBIFTaxonhigherTaxasuperfamily: {
    prop: "subjectFinBIFTaxon.higherTaxa.superfamily",
    filterType: "string",
    defaultValue: null,
  },
  subjectFinBIFTaxonhigherTaxafamily: {
    prop: "subjectFinBIFTaxon.higherTaxa.family",
    filterType: "string",
    defaultValue: null,
  },
  subjectFinBIFTaxonhigherTaxasubfamily: {
    prop: "subjectFinBIFTaxon.higherTaxa.subfamily",
    filterType: "string",
    defaultValue: null,
  },
  subjectFinBIFTaxonhigherTaxatribe: {
    prop: "subjectFinBIFTaxon.higherTaxa.tribe",
    filterType: "string",
    defaultValue: null,
  },
  subjectFinBIFTaxonhigherTaxasubtribe: {
    prop: "subjectFinBIFTaxon.higherTaxa.subtribe",
    filterType: "string",
    defaultValue: null,
  },
  subjectFinBIFTaxonhigherTaxagenus: {
    prop: "subjectFinBIFTaxon.higherTaxa.genus",
    filterType: "string",
    defaultValue: null,
  },
  subjectFinBIFTaxoniucnStatus: {
    prop: "subjectFinBIFTaxon.iucnStatus",
    filterType: "enum",
    defaultValue: null,
    range: [
      "MX.iucnEX",
      "MX.iucnEW",
      "MX.iucnRE",
      "MX.iucnCR",
      "MX.iucnEN",
      "MX.iucnVU",
      "MX.iucnNT",
      "MX.iucnLC",
      "MX.iucnDD",
      "MX.iucnNA",
      "MX.iucnNE",
    ],
  },
  subjectFinBIFTaxonprimaryHabitat: {
    prop: "subjectFinBIFTaxon.primaryHabitat",
    filterType: "enum",
    defaultValue: null,
    range: [
      "MKV.habitatM",
      "MKV.habitatMk",
      "MKV.habitatMkk",
      "MKV.habitatMkt",
      "MKV.habitatMl",
      "MKV.habitatMlt",
      "MKV.habitatMlk",
      "MKV.habitatMt",
      "MKV.habitatMtl",
      "MKV.habitatS",
      "MKV.habitatSl",
      "MKV.habitatSla",
      "MKV.habitatSlr",
      "MKV.habitatSlk",
      "MKV.habitatSn",
      "MKV.habitatSnk",
      "MKV.habitatSnr",
      "MKV.habitatSr",
      "MKV.habitatSrk",
      "MKV.habitatSrr",
      "MKV.habitatSk",
      "MKV.habitatSkk",
      "MKV.habitatSkr",
      "MKV.habitatV",
      "MKV.habitatVi",
      "MKV.habitatVik",
      "MKV.habitatVim",
      "MKV.habitatVis",
      "MKV.habitatVih",
      "MKV.habitatVie",
      "MKV.habitatVip",
      "MKV.habitatVs",
      "MKV.habitatVsk",
      "MKV.habitatVsr",
      "MKV.habitatVa",
      "MKV.habitatVj",
      "MKV.habitatVp",
      "MKV.habitatVk",
      "MKV.habitatVl",
      "MKV.habitatR",
      "MKV.habitatRi",
      "MKV.habitatRim",
      "MKV.habitatRimt",
      "MKV.habitatRiml",
      "MKV.habitatRip",
      "MKV.habitatRin",
      "MKV.habitatRil",
      "MKV.habitatRir",
      "MKV.habitatRis",
      "MKV.habitatRih",
      "MKV.habitatRit",
      "MKV.habitatRj",
      "MKV.habitatRjm",
      "MKV.habitatRjmt",
      "MKV.habitatRjml",
      "MKV.habitatRjp",
      "MKV.habitatRjn",
      "MKV.habitatRjl",
      "MKV.habitatRjr",
      "MKV.habitatRjs",
      "MKV.habitatRjh",
      "MKV.habitatRjt",
      "MKV.habitatK",
      "MKV.habitatKk",
      "MKV.habitatKs",
      "MKV.habitatKr",
      "MKV.habitatKl",
      "MKV.habitatKm",
      "MKV.habitatT",
      "MKV.habitatTk",
      "MKV.habitatTn",
      "MKV.habitatTu",
      "MKV.habitatTp",
      "MKV.habitatTl",
      "MKV.habitatTll",
      "MKV.habitatTlk",
      "MKV.habitatTls",
      "MKV.habitatTlr",
      "MKV.habitatTl\u00E4",
      "MKV.habitatTs",
      "MKV.habitatTj",
      "MKV.habitatTv",
      "MKV.habitatTa",
      "MKV.habitatI",
      "MKV.habitatIn",
      "MKV.habitatIt",
      "MKV.habitatIh",
      "MKV.habitatIk",
      "MKV.habitatIo",
      "MKV.habitatIv",
      "MKV.habitatIp",
      "MKV.habitatIu",
      "MKV.habitatIr",
      "MKV.habitatU",
    ],
  },
  subjectFinBIFTaxonhabitatSpecifiers: {
    prop: "subjectFinBIFTaxon.habitatSpecifiers",
    filterType: "array",
    defaultValue: null,
    elementType: {
      _tag: "enum",
      variants: [
        "MKV.habitatSpecificTypeV",
        "MKV.habitatSpecificTypeH",
        "MKV.habitatSpecificTypeP",
        "MKV.habitatSpecificTypeJ",
        "MKV.habitatSpecificTypePAK",
        "MKV.habitatSpecificTypeVAK",
        "MKV.habitatSpecificTypeRA",
        "MKV.habitatSpecificTypeKA",
        "MKV.habitatSpecificTypeKE",
        "MKV.habitatSpecificTypeCA",
      ],
    },
  },
  subjectFinBIFTaxonsensitive: {
    prop: "subjectFinBIFTaxon.sensitive",
    filterType: "boolean",
    defaultValue: null,
  },
  subjectGBIFTaxonid: {
    prop: "subjectGBIFTaxon.id",
    filterType: "string",
    defaultValue: null,
  },
  subjectGBIFTaxontaxonomicOrder: {
    prop: "subjectGBIFTaxon.taxonomicOrder",
    filterType: "number",
    defaultValue: null,
  },
  subjectGBIFTaxontaxonRank: {
    prop: "subjectGBIFTaxon.taxonRank",
    filterType: "string",
    defaultValue: null,
  },
  subjectGBIFTaxonscientificName: {
    prop: "subjectGBIFTaxon.scientificName",
    filterType: "string",
    defaultValue: null,
  },
  subjectGBIFTaxoncursiveName: {
    prop: "subjectGBIFTaxon.cursiveName",
    filterType: "boolean",
    defaultValue: null,
  },
  subjectGBIFTaxonauthor: {
    prop: "subjectGBIFTaxon.author",
    filterType: "string",
    defaultValue: null,
  },
  subjectGBIFTaxonhigherTaxadomain: {
    prop: "subjectGBIFTaxon.higherTaxa.domain",
    filterType: "string",
    defaultValue: null,
  },
  subjectGBIFTaxonhigherTaxakingdom: {
    prop: "subjectGBIFTaxon.higherTaxa.kingdom",
    filterType: "string",
    defaultValue: null,
  },
  subjectGBIFTaxonhigherTaxaphylum: {
    prop: "subjectGBIFTaxon.higherTaxa.phylum",
    filterType: "string",
    defaultValue: null,
  },
  subjectGBIFTaxonhigherTaxasubphylum: {
    prop: "subjectGBIFTaxon.higherTaxa.subphylum",
    filterType: "string",
    defaultValue: null,
  },
  subjectGBIFTaxonhigherTaxadivision: {
    prop: "subjectGBIFTaxon.higherTaxa.division",
    filterType: "string",
    defaultValue: null,
  },
  subjectGBIFTaxonhigherTaxaclass: {
    prop: "subjectGBIFTaxon.higherTaxa.class",
    filterType: "string",
    defaultValue: null,
  },
  subjectGBIFTaxonhigherTaxasubclass: {
    prop: "subjectGBIFTaxon.higherTaxa.subclass",
    filterType: "string",
    defaultValue: null,
  },
  subjectGBIFTaxonhigherTaxaorder: {
    prop: "subjectGBIFTaxon.higherTaxa.order",
    filterType: "string",
    defaultValue: null,
  },
  subjectGBIFTaxonhigherTaxasuborder: {
    prop: "subjectGBIFTaxon.higherTaxa.suborder",
    filterType: "string",
    defaultValue: null,
  },
  subjectGBIFTaxonhigherTaxasuperfamily: {
    prop: "subjectGBIFTaxon.higherTaxa.superfamily",
    filterType: "string",
    defaultValue: null,
  },
  subjectGBIFTaxonhigherTaxafamily: {
    prop: "subjectGBIFTaxon.higherTaxa.family",
    filterType: "string",
    defaultValue: null,
  },
  subjectGBIFTaxonhigherTaxasubfamily: {
    prop: "subjectGBIFTaxon.higherTaxa.subfamily",
    filterType: "string",
    defaultValue: null,
  },
  subjectGBIFTaxonhigherTaxatribe: {
    prop: "subjectGBIFTaxon.higherTaxa.tribe",
    filterType: "string",
    defaultValue: null,
  },
  subjectGBIFTaxonhigherTaxasubtribe: {
    prop: "subjectGBIFTaxon.higherTaxa.subtribe",
    filterType: "string",
    defaultValue: null,
  },
  subjectGBIFTaxonhigherTaxagenus: {
    prop: "subjectGBIFTaxon.higherTaxa.genus",
    filterType: "string",
    defaultValue: null,
  },
  subjectGBIFTaxoniucnStatus: {
    prop: "subjectGBIFTaxon.iucnStatus",
    filterType: "enum",
    defaultValue: null,
    range: [
      "MX.iucnEX",
      "MX.iucnEW",
      "MX.iucnRE",
      "MX.iucnCR",
      "MX.iucnEN",
      "MX.iucnVU",
      "MX.iucnNT",
      "MX.iucnLC",
      "MX.iucnDD",
      "MX.iucnNA",
      "MX.iucnNE",
    ],
  },
  subjectGBIFTaxonprimaryHabitat: {
    prop: "subjectGBIFTaxon.primaryHabitat",
    filterType: "enum",
    defaultValue: null,
    range: [
      "MKV.habitatM",
      "MKV.habitatMk",
      "MKV.habitatMkk",
      "MKV.habitatMkt",
      "MKV.habitatMl",
      "MKV.habitatMlt",
      "MKV.habitatMlk",
      "MKV.habitatMt",
      "MKV.habitatMtl",
      "MKV.habitatS",
      "MKV.habitatSl",
      "MKV.habitatSla",
      "MKV.habitatSlr",
      "MKV.habitatSlk",
      "MKV.habitatSn",
      "MKV.habitatSnk",
      "MKV.habitatSnr",
      "MKV.habitatSr",
      "MKV.habitatSrk",
      "MKV.habitatSrr",
      "MKV.habitatSk",
      "MKV.habitatSkk",
      "MKV.habitatSkr",
      "MKV.habitatV",
      "MKV.habitatVi",
      "MKV.habitatVik",
      "MKV.habitatVim",
      "MKV.habitatVis",
      "MKV.habitatVih",
      "MKV.habitatVie",
      "MKV.habitatVip",
      "MKV.habitatVs",
      "MKV.habitatVsk",
      "MKV.habitatVsr",
      "MKV.habitatVa",
      "MKV.habitatVj",
      "MKV.habitatVp",
      "MKV.habitatVk",
      "MKV.habitatVl",
      "MKV.habitatR",
      "MKV.habitatRi",
      "MKV.habitatRim",
      "MKV.habitatRimt",
      "MKV.habitatRiml",
      "MKV.habitatRip",
      "MKV.habitatRin",
      "MKV.habitatRil",
      "MKV.habitatRir",
      "MKV.habitatRis",
      "MKV.habitatRih",
      "MKV.habitatRit",
      "MKV.habitatRj",
      "MKV.habitatRjm",
      "MKV.habitatRjmt",
      "MKV.habitatRjml",
      "MKV.habitatRjp",
      "MKV.habitatRjn",
      "MKV.habitatRjl",
      "MKV.habitatRjr",
      "MKV.habitatRjs",
      "MKV.habitatRjh",
      "MKV.habitatRjt",
      "MKV.habitatK",
      "MKV.habitatKk",
      "MKV.habitatKs",
      "MKV.habitatKr",
      "MKV.habitatKl",
      "MKV.habitatKm",
      "MKV.habitatT",
      "MKV.habitatTk",
      "MKV.habitatTn",
      "MKV.habitatTu",
      "MKV.habitatTp",
      "MKV.habitatTl",
      "MKV.habitatTll",
      "MKV.habitatTlk",
      "MKV.habitatTls",
      "MKV.habitatTlr",
      "MKV.habitatTl\u00E4",
      "MKV.habitatTs",
      "MKV.habitatTj",
      "MKV.habitatTv",
      "MKV.habitatTa",
      "MKV.habitatI",
      "MKV.habitatIn",
      "MKV.habitatIt",
      "MKV.habitatIh",
      "MKV.habitatIk",
      "MKV.habitatIo",
      "MKV.habitatIv",
      "MKV.habitatIp",
      "MKV.habitatIu",
      "MKV.habitatIr",
      "MKV.habitatU",
    ],
  },
  subjectGBIFTaxonhabitatSpecifiers: {
    prop: "subjectGBIFTaxon.habitatSpecifiers",
    filterType: "array",
    defaultValue: null,
    elementType: {
      _tag: "enum",
      variants: [
        "MKV.habitatSpecificTypeV",
        "MKV.habitatSpecificTypeH",
        "MKV.habitatSpecificTypeP",
        "MKV.habitatSpecificTypeJ",
        "MKV.habitatSpecificTypePAK",
        "MKV.habitatSpecificTypeVAK",
        "MKV.habitatSpecificTypeRA",
        "MKV.habitatSpecificTypeKA",
        "MKV.habitatSpecificTypeKE",
        "MKV.habitatSpecificTypeCA",
      ],
    },
  },
  subjectGBIFTaxonsensitive: {
    prop: "subjectGBIFTaxon.sensitive",
    filterType: "boolean",
    defaultValue: null,
  },
  objectTaxonLifeStage: {
    prop: "objectTaxonLifeStage",
    filterType: "enum",
    defaultValue: null,
    range: [
      "MY.lifeStageAdult",
      "MY.lifeStageNymph",
      "MY.lifeStageLarva",
      "MY.lifeStageEgg",
      "MY.lifeStagePupa",
      "MY.lifeStageJuvenile",
      "MY.lifeStageSubimago",
      "MY.lifeStageImmature",
      "MY.lifeStageFertile",
      "MY.lifeStageSterile",
      "MY.lifeStageTadpole",
      "MY.lifeStageEmbryo",
      "MY.lifeStageSubadult",
      "MY.lifeStageMature",
      "MY.lifeStagePullus",
      "MY.lifeStageHatchedEgg",
      "MY.lifeStageHatchedPupa",
      "MY.lifeStageGall",
      "MY.lifeStageMarks",
      "MY.lifeStageTriungulin",
    ],
  },
  objectTaxonVerbatim: {
    prop: "objectTaxonVerbatim",
    filterType: "string",
    defaultValue: null,
  },
  objectFinBIFTaxonid: {
    prop: "objectFinBIFTaxon.id",
    filterType: "string",
    defaultValue: null,
  },
  objectFinBIFTaxontaxonomicOrder: {
    prop: "objectFinBIFTaxon.taxonomicOrder",
    filterType: "number",
    defaultValue: null,
  },
  objectFinBIFTaxontaxonRank: {
    prop: "objectFinBIFTaxon.taxonRank",
    filterType: "string",
    defaultValue: null,
  },
  objectFinBIFTaxonscientificName: {
    prop: "objectFinBIFTaxon.scientificName",
    filterType: "string",
    defaultValue: null,
  },
  objectFinBIFTaxoncursiveName: {
    prop: "objectFinBIFTaxon.cursiveName",
    filterType: "boolean",
    defaultValue: null,
  },
  objectFinBIFTaxonauthor: {
    prop: "objectFinBIFTaxon.author",
    filterType: "string",
    defaultValue: null,
  },
  objectFinBIFTaxonhigherTaxadomain: {
    prop: "objectFinBIFTaxon.higherTaxa.domain",
    filterType: "string",
    defaultValue: null,
  },
  objectFinBIFTaxonhigherTaxakingdom: {
    prop: "objectFinBIFTaxon.higherTaxa.kingdom",
    filterType: "string",
    defaultValue: null,
  },
  objectFinBIFTaxonhigherTaxaphylum: {
    prop: "objectFinBIFTaxon.higherTaxa.phylum",
    filterType: "string",
    defaultValue: null,
  },
  objectFinBIFTaxonhigherTaxasubphylum: {
    prop: "objectFinBIFTaxon.higherTaxa.subphylum",
    filterType: "string",
    defaultValue: null,
  },
  objectFinBIFTaxonhigherTaxadivision: {
    prop: "objectFinBIFTaxon.higherTaxa.division",
    filterType: "string",
    defaultValue: null,
  },
  objectFinBIFTaxonhigherTaxaclass: {
    prop: "objectFinBIFTaxon.higherTaxa.class",
    filterType: "string",
    defaultValue: null,
  },
  objectFinBIFTaxonhigherTaxasubclass: {
    prop: "objectFinBIFTaxon.higherTaxa.subclass",
    filterType: "string",
    defaultValue: null,
  },
  objectFinBIFTaxonhigherTaxaorder: {
    prop: "objectFinBIFTaxon.higherTaxa.order",
    filterType: "string",
    defaultValue: null,
  },
  objectFinBIFTaxonhigherTaxasuborder: {
    prop: "objectFinBIFTaxon.higherTaxa.suborder",
    filterType: "string",
    defaultValue: null,
  },
  objectFinBIFTaxonhigherTaxasuperfamily: {
    prop: "objectFinBIFTaxon.higherTaxa.superfamily",
    filterType: "string",
    defaultValue: null,
  },
  objectFinBIFTaxonhigherTaxafamily: {
    prop: "objectFinBIFTaxon.higherTaxa.family",
    filterType: "string",
    defaultValue: null,
  },
  objectFinBIFTaxonhigherTaxasubfamily: {
    prop: "objectFinBIFTaxon.higherTaxa.subfamily",
    filterType: "string",
    defaultValue: null,
  },
  objectFinBIFTaxonhigherTaxatribe: {
    prop: "objectFinBIFTaxon.higherTaxa.tribe",
    filterType: "string",
    defaultValue: null,
  },
  objectFinBIFTaxonhigherTaxasubtribe: {
    prop: "objectFinBIFTaxon.higherTaxa.subtribe",
    filterType: "string",
    defaultValue: null,
  },
  objectFinBIFTaxonhigherTaxagenus: {
    prop: "objectFinBIFTaxon.higherTaxa.genus",
    filterType: "string",
    defaultValue: null,
  },
  objectFinBIFTaxoniucnStatus: {
    prop: "objectFinBIFTaxon.iucnStatus",
    filterType: "enum",
    defaultValue: null,
    range: [
      "MX.iucnEX",
      "MX.iucnEW",
      "MX.iucnRE",
      "MX.iucnCR",
      "MX.iucnEN",
      "MX.iucnVU",
      "MX.iucnNT",
      "MX.iucnLC",
      "MX.iucnDD",
      "MX.iucnNA",
      "MX.iucnNE",
    ],
  },
  objectFinBIFTaxonprimaryHabitat: {
    prop: "objectFinBIFTaxon.primaryHabitat",
    filterType: "enum",
    defaultValue: null,
    range: [
      "MKV.habitatM",
      "MKV.habitatMk",
      "MKV.habitatMkk",
      "MKV.habitatMkt",
      "MKV.habitatMl",
      "MKV.habitatMlt",
      "MKV.habitatMlk",
      "MKV.habitatMt",
      "MKV.habitatMtl",
      "MKV.habitatS",
      "MKV.habitatSl",
      "MKV.habitatSla",
      "MKV.habitatSlr",
      "MKV.habitatSlk",
      "MKV.habitatSn",
      "MKV.habitatSnk",
      "MKV.habitatSnr",
      "MKV.habitatSr",
      "MKV.habitatSrk",
      "MKV.habitatSrr",
      "MKV.habitatSk",
      "MKV.habitatSkk",
      "MKV.habitatSkr",
      "MKV.habitatV",
      "MKV.habitatVi",
      "MKV.habitatVik",
      "MKV.habitatVim",
      "MKV.habitatVis",
      "MKV.habitatVih",
      "MKV.habitatVie",
      "MKV.habitatVip",
      "MKV.habitatVs",
      "MKV.habitatVsk",
      "MKV.habitatVsr",
      "MKV.habitatVa",
      "MKV.habitatVj",
      "MKV.habitatVp",
      "MKV.habitatVk",
      "MKV.habitatVl",
      "MKV.habitatR",
      "MKV.habitatRi",
      "MKV.habitatRim",
      "MKV.habitatRimt",
      "MKV.habitatRiml",
      "MKV.habitatRip",
      "MKV.habitatRin",
      "MKV.habitatRil",
      "MKV.habitatRir",
      "MKV.habitatRis",
      "MKV.habitatRih",
      "MKV.habitatRit",
      "MKV.habitatRj",
      "MKV.habitatRjm",
      "MKV.habitatRjmt",
      "MKV.habitatRjml",
      "MKV.habitatRjp",
      "MKV.habitatRjn",
      "MKV.habitatRjl",
      "MKV.habitatRjr",
      "MKV.habitatRjs",
      "MKV.habitatRjh",
      "MKV.habitatRjt",
      "MKV.habitatK",
      "MKV.habitatKk",
      "MKV.habitatKs",
      "MKV.habitatKr",
      "MKV.habitatKl",
      "MKV.habitatKm",
      "MKV.habitatT",
      "MKV.habitatTk",
      "MKV.habitatTn",
      "MKV.habitatTu",
      "MKV.habitatTp",
      "MKV.habitatTl",
      "MKV.habitatTll",
      "MKV.habitatTlk",
      "MKV.habitatTls",
      "MKV.habitatTlr",
      "MKV.habitatTl\u00E4",
      "MKV.habitatTs",
      "MKV.habitatTj",
      "MKV.habitatTv",
      "MKV.habitatTa",
      "MKV.habitatI",
      "MKV.habitatIn",
      "MKV.habitatIt",
      "MKV.habitatIh",
      "MKV.habitatIk",
      "MKV.habitatIo",
      "MKV.habitatIv",
      "MKV.habitatIp",
      "MKV.habitatIu",
      "MKV.habitatIr",
      "MKV.habitatU",
    ],
  },
  objectFinBIFTaxonhabitatSpecifiers: {
    prop: "objectFinBIFTaxon.habitatSpecifiers",
    filterType: "array",
    defaultValue: null,
    elementType: {
      _tag: "enum",
      variants: [
        "MKV.habitatSpecificTypeV",
        "MKV.habitatSpecificTypeH",
        "MKV.habitatSpecificTypeP",
        "MKV.habitatSpecificTypeJ",
        "MKV.habitatSpecificTypePAK",
        "MKV.habitatSpecificTypeVAK",
        "MKV.habitatSpecificTypeRA",
        "MKV.habitatSpecificTypeKA",
        "MKV.habitatSpecificTypeKE",
        "MKV.habitatSpecificTypeCA",
      ],
    },
  },
  objectFinBIFTaxonsensitive: {
    prop: "objectFinBIFTaxon.sensitive",
    filterType: "boolean",
    defaultValue: null,
  },
  objectGBIFTaxonid: {
    prop: "objectGBIFTaxon.id",
    filterType: "string",
    defaultValue: null,
  },
  objectGBIFTaxontaxonomicOrder: {
    prop: "objectGBIFTaxon.taxonomicOrder",
    filterType: "number",
    defaultValue: null,
  },
  objectGBIFTaxontaxonRank: {
    prop: "objectGBIFTaxon.taxonRank",
    filterType: "string",
    defaultValue: null,
  },
  objectGBIFTaxonscientificName: {
    prop: "objectGBIFTaxon.scientificName",
    filterType: "string",
    defaultValue: null,
  },
  objectGBIFTaxoncursiveName: {
    prop: "objectGBIFTaxon.cursiveName",
    filterType: "boolean",
    defaultValue: null,
  },
  objectGBIFTaxonauthor: {
    prop: "objectGBIFTaxon.author",
    filterType: "string",
    defaultValue: null,
  },
  objectGBIFTaxonhigherTaxadomain: {
    prop: "objectGBIFTaxon.higherTaxa.domain",
    filterType: "string",
    defaultValue: null,
  },
  objectGBIFTaxonhigherTaxakingdom: {
    prop: "objectGBIFTaxon.higherTaxa.kingdom",
    filterType: "string",
    defaultValue: null,
  },
  objectGBIFTaxonhigherTaxaphylum: {
    prop: "objectGBIFTaxon.higherTaxa.phylum",
    filterType: "string",
    defaultValue: null,
  },
  objectGBIFTaxonhigherTaxasubphylum: {
    prop: "objectGBIFTaxon.higherTaxa.subphylum",
    filterType: "string",
    defaultValue: null,
  },
  objectGBIFTaxonhigherTaxadivision: {
    prop: "objectGBIFTaxon.higherTaxa.division",
    filterType: "string",
    defaultValue: null,
  },
  objectGBIFTaxonhigherTaxaclass: {
    prop: "objectGBIFTaxon.higherTaxa.class",
    filterType: "string",
    defaultValue: null,
  },
  objectGBIFTaxonhigherTaxasubclass: {
    prop: "objectGBIFTaxon.higherTaxa.subclass",
    filterType: "string",
    defaultValue: null,
  },
  objectGBIFTaxonhigherTaxaorder: {
    prop: "objectGBIFTaxon.higherTaxa.order",
    filterType: "string",
    defaultValue: null,
  },
  objectGBIFTaxonhigherTaxasuborder: {
    prop: "objectGBIFTaxon.higherTaxa.suborder",
    filterType: "string",
    defaultValue: null,
  },
  objectGBIFTaxonhigherTaxasuperfamily: {
    prop: "objectGBIFTaxon.higherTaxa.superfamily",
    filterType: "string",
    defaultValue: null,
  },
  objectGBIFTaxonhigherTaxafamily: {
    prop: "objectGBIFTaxon.higherTaxa.family",
    filterType: "string",
    defaultValue: null,
  },
  objectGBIFTaxonhigherTaxasubfamily: {
    prop: "objectGBIFTaxon.higherTaxa.subfamily",
    filterType: "string",
    defaultValue: null,
  },
  objectGBIFTaxonhigherTaxatribe: {
    prop: "objectGBIFTaxon.higherTaxa.tribe",
    filterType: "string",
    defaultValue: null,
  },
  objectGBIFTaxonhigherTaxasubtribe: {
    prop: "objectGBIFTaxon.higherTaxa.subtribe",
    filterType: "string",
    defaultValue: null,
  },
  objectGBIFTaxonhigherTaxagenus: {
    prop: "objectGBIFTaxon.higherTaxa.genus",
    filterType: "string",
    defaultValue: null,
  },
  objectGBIFTaxoniucnStatus: {
    prop: "objectGBIFTaxon.iucnStatus",
    filterType: "enum",
    defaultValue: null,
    range: [
      "MX.iucnEX",
      "MX.iucnEW",
      "MX.iucnRE",
      "MX.iucnCR",
      "MX.iucnEN",
      "MX.iucnVU",
      "MX.iucnNT",
      "MX.iucnLC",
      "MX.iucnDD",
      "MX.iucnNA",
      "MX.iucnNE",
    ],
  },
  objectGBIFTaxonprimaryHabitat: {
    prop: "objectGBIFTaxon.primaryHabitat",
    filterType: "enum",
    defaultValue: null,
    range: [
      "MKV.habitatM",
      "MKV.habitatMk",
      "MKV.habitatMkk",
      "MKV.habitatMkt",
      "MKV.habitatMl",
      "MKV.habitatMlt",
      "MKV.habitatMlk",
      "MKV.habitatMt",
      "MKV.habitatMtl",
      "MKV.habitatS",
      "MKV.habitatSl",
      "MKV.habitatSla",
      "MKV.habitatSlr",
      "MKV.habitatSlk",
      "MKV.habitatSn",
      "MKV.habitatSnk",
      "MKV.habitatSnr",
      "MKV.habitatSr",
      "MKV.habitatSrk",
      "MKV.habitatSrr",
      "MKV.habitatSk",
      "MKV.habitatSkk",
      "MKV.habitatSkr",
      "MKV.habitatV",
      "MKV.habitatVi",
      "MKV.habitatVik",
      "MKV.habitatVim",
      "MKV.habitatVis",
      "MKV.habitatVih",
      "MKV.habitatVie",
      "MKV.habitatVip",
      "MKV.habitatVs",
      "MKV.habitatVsk",
      "MKV.habitatVsr",
      "MKV.habitatVa",
      "MKV.habitatVj",
      "MKV.habitatVp",
      "MKV.habitatVk",
      "MKV.habitatVl",
      "MKV.habitatR",
      "MKV.habitatRi",
      "MKV.habitatRim",
      "MKV.habitatRimt",
      "MKV.habitatRiml",
      "MKV.habitatRip",
      "MKV.habitatRin",
      "MKV.habitatRil",
      "MKV.habitatRir",
      "MKV.habitatRis",
      "MKV.habitatRih",
      "MKV.habitatRit",
      "MKV.habitatRj",
      "MKV.habitatRjm",
      "MKV.habitatRjmt",
      "MKV.habitatRjml",
      "MKV.habitatRjp",
      "MKV.habitatRjn",
      "MKV.habitatRjl",
      "MKV.habitatRjr",
      "MKV.habitatRjs",
      "MKV.habitatRjh",
      "MKV.habitatRjt",
      "MKV.habitatK",
      "MKV.habitatKk",
      "MKV.habitatKs",
      "MKV.habitatKr",
      "MKV.habitatKl",
      "MKV.habitatKm",
      "MKV.habitatT",
      "MKV.habitatTk",
      "MKV.habitatTn",
      "MKV.habitatTu",
      "MKV.habitatTp",
      "MKV.habitatTl",
      "MKV.habitatTll",
      "MKV.habitatTlk",
      "MKV.habitatTls",
      "MKV.habitatTlr",
      "MKV.habitatTl\u00E4",
      "MKV.habitatTs",
      "MKV.habitatTj",
      "MKV.habitatTv",
      "MKV.habitatTa",
      "MKV.habitatI",
      "MKV.habitatIn",
      "MKV.habitatIt",
      "MKV.habitatIh",
      "MKV.habitatIk",
      "MKV.habitatIo",
      "MKV.habitatIv",
      "MKV.habitatIp",
      "MKV.habitatIu",
      "MKV.habitatIr",
      "MKV.habitatU",
    ],
  },
  objectGBIFTaxonhabitatSpecifiers: {
    prop: "objectGBIFTaxon.habitatSpecifiers",
    filterType: "array",
    defaultValue: null,
    elementType: {
      _tag: "enum",
      variants: [
        "MKV.habitatSpecificTypeV",
        "MKV.habitatSpecificTypeH",
        "MKV.habitatSpecificTypeP",
        "MKV.habitatSpecificTypeJ",
        "MKV.habitatSpecificTypePAK",
        "MKV.habitatSpecificTypeVAK",
        "MKV.habitatSpecificTypeRA",
        "MKV.habitatSpecificTypeKA",
        "MKV.habitatSpecificTypeKE",
        "MKV.habitatSpecificTypeCA",
      ],
    },
  },
  objectGBIFTaxonsensitive: {
    prop: "objectGBIFTaxon.sensitive",
    filterType: "boolean",
    defaultValue: null,
  },
  warnings: { prop: "warnings", filterType: "boolean", defaultValue: null },
  measurementRemarks: {
    prop: "measurementRemarks",
    filterType: "string",
    defaultValue: null,
  },
  reference: { prop: "reference", filterType: "string", defaultValue: null },
  datasetid: { prop: "dataset.id", filterType: "string", defaultValue: null },
  datasetname: {
    prop: "dataset.name",
    filterType: "string",
    defaultValue: null,
  },
  datasetdescription: {
    prop: "dataset.description",
    filterType: "string",
    defaultValue: null,
  },
  datasetcitation: {
    prop: "dataset.citation",
    filterType: "string",
    defaultValue: null,
  },
  datasetintellectualOwner: {
    prop: "dataset.intellectualOwner",
    filterType: "string",
    defaultValue: null,
  },
  datasetpersonResponsible: {
    prop: "dataset.personResponsible",
    filterType: "string",
    defaultValue: null,
  },
  datasetcontactEmail: {
    prop: "dataset.contactEmail",
    filterType: "string",
    defaultValue: null,
  },
  datasetmethods: {
    prop: "dataset.methods",
    filterType: "string",
    defaultValue: null,
  },
  datasetcoverageBasis: {
    prop: "dataset.coverageBasis",
    filterType: "string",
    defaultValue: null,
  },
  datasetfinbifDOI: {
    prop: "dataset.finbifDOI",
    filterType: "string",
    defaultValue: null,
  },
  datasetgbifDOI: {
    prop: "dataset.gbifDOI",
    filterType: "string",
    defaultValue: null,
  },
  datasetadditionalIdentifiers: {
    prop: "dataset.additionalIdentifiers",
    filterType: "array",
    defaultValue: null,
    elementType: { _tag: "string" },
  },
  license: {
    prop: "license",
    filterType: "enum",
    defaultValue: null,
    range: [
      "MZ.intellectualRightsCC-BY-SA-4.0",
      "MZ.intellectualRightsCC-BY-NC-4.0",
      "MZ.intellectualRightsCC-BY-NC-SA-4.0",
      "MZ.intellectualRightsCC-BY-4.0",
      "MZ.intellectualRightsCC0-4.0",
      "MZ.intellectualRightsODBL-1.0",
      "MZ.intellectualRightsPD",
      "MZ.intellectualRightsARR",
      "MZ.intellectualRightsCC-BY-2.0",
      "MZ.intellectualRightsCC-BY-SA-2.0",
      "MZ.intellectualRightsCC-BY-SA-2.0-DE",
      "MZ.intellectualRightsCC-BY-NC-2.0",
      "MZ.intellectualRightsCC-BY-NC-SA-2.0",
      "MZ.intellectualRightsCC-BY-NC-ND-2.0",
      "MZ.intellectualRightsCC-BY-SA-2.5",
      "MZ.intellectualRightsCC-BY-SA-2.5-SE",
      "MZ.intellectualRightsCC-BY-3.0",
      "MZ.intellectualRightsCC-BY-SA-3.0",
      "MZ.intellectualRightsCC-BY-NC-SA-3.0",
      "MZ.intellectualRightsCC-BY-ND-4.0",
      "MZ.intellectualRightsCC-BY-NC-ND-4.0",
      "MY.intellectualRightsCC-BY",
      "MY.intellectualRightsCC0",
    ],
  },
};
