/* tslint:disable */
export interface DwETL_Quality {
  issue?: 'REPORTED_UNRELIABLE' | 'MEDIA_ISSUE' | 'INVALID_CREATED_DATE' | 'INVALID_MODIFIED_DATE' | 'COORDINATES_COUNTRY_MISMATCH' | 'COORDINATES_MUNICIPALITY_MISMATCH' | 'TOO_LARGE_AREA' | 'INVALID_GEO' | 'INVALID_YKJ_COORDINATES' | 'INVALID_EUREF_COORDINATES' | 'INVALID_WGS84_COORDINATES' | 'DATE_END_BEFORE_BEGIN' | 'DATE_END_GIVEN_WITHOUT_BEGIN' | 'DATE_IN_FUTURE' | 'DATE_TOO_FAR_IN_THE_PAST' | 'INVALID_DATE' | 'RECORD_BASIS_MISSING' | 'INVALID_HOUR' | 'INVALID_MINUTE' | 'TIME_END_BEFORE_BEGIN';
  source?: 'AUTOMATED_FINBIF_VALIDATION' | 'ORIGINAL_DOCUMENT' | 'COLLECTION_QUALITY_RATING' | 'USER_ANNOTATION' | 'EXPERT_ANNOTATION' | 'ADMIN_ANNOTATION' | 'ORIGINAL_OBSERVER';
  message?: string;
}
