/* tslint:disable:max-line-length */
/**
 * API documentation
 * Access token is needed to use this API. To get a token, send a POST request with your email address to /api-users endpoint and one will be send to your. Each endpoint bellow has more information on how to use this API. If you have any questions you can contact us at helpdesk@laji.fi.  You can find more documentation [here](https://laji.fi/about/806).  ##Endpoints  Observations and collections * Warehouse - Observation Data Warehouse API * Collection - Collection metadata * Source - Information sources (IT systems) * Annotation - Quality control   Taxonomy * Taxa - Taxonomy API * InformalTaxonGroup - Informal taxon groups are used in taxa and warehouse endpoints * Publication - Scientific publications * Checklist - Mainly you only work with one checklits: the FinBIF master checklist. There are others.   Other master data * Metadata - Variable descriptions * Area - Countries, municipalities and biogeographical provinces of Finland, etc. * Person - Information about people.   Helpers * APIUser - Register as an API user * Autocomplete - For making an autocomplete filed for taxa, collections or persons (friends) * PersonToken - Information about an authorized person   Vihko observation system * Form - Form definition * Document - Document instance of a form * Image - Image of a document   Laji.fi portal * Feedback - Feedback form API * Information - CMS content of information pages * Logger - Error logging from user's browsers to FinBIF * News - News
 *
 * OpenAPI spec version: 0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface DwSingleGatheringInterpretations {
  coordinateAccuracy?: number;
  sourceOfCoordinates?: DwSingleGatheringInterpretations.SourceOfCoordinatesEnum;
  countryDisplayname?: string;
  biogeographicalProvinceDisplayname?: string;
  municipalityDisplayname?: string;
  sourceOfCountry?: DwSingleGatheringInterpretations.SourceOfCountryEnum;
  sourceOfBiogeographicalProvince?: DwSingleGatheringInterpretations.SourceOfBiogeographicalProvinceEnum;
  sourceOfFinnishMunicipality?: DwSingleGatheringInterpretations.SourceOfFinnishMunicipalityEnum;
  biogeographicalProvince?: string;
  biogeographicalProvinces?: Array<string>;
  country?: string;
  finnishMunicipalities?: Array<string>;
  finnishMunicipality?: string;
}

export namespace DwSingleGatheringInterpretations {
  export type SourceOfCoordinatesEnum =
    'COORDINATES'
    | 'COORDINATE_CENTERPOINT'
    | 'REPORTED_VALUE'
    | 'FINNISH_MUNICIPALITY'
    | 'OLD_FINNISH_MUNICIPALITY';
  export const SourceOfCoordinatesEnum = {
    COORDINATES: 'COORDINATES' as SourceOfCoordinatesEnum,
    COORDINATECENTERPOINT: 'COORDINATE_CENTERPOINT' as SourceOfCoordinatesEnum,
    REPORTEDVALUE: 'REPORTED_VALUE' as SourceOfCoordinatesEnum,
    FINNISHMUNICIPALITY: 'FINNISH_MUNICIPALITY' as SourceOfCoordinatesEnum,
    OLDFINNISHMUNICIPALITY: 'OLD_FINNISH_MUNICIPALITY' as SourceOfCoordinatesEnum
  };
  export type SourceOfCountryEnum =
    'COORDINATES'
    | 'COORDINATE_CENTERPOINT'
    | 'REPORTED_VALUE'
    | 'FINNISH_MUNICIPALITY'
    | 'OLD_FINNISH_MUNICIPALITY';
  export const SourceOfCountryEnum = {
    COORDINATES: 'COORDINATES' as SourceOfCountryEnum,
    COORDINATECENTERPOINT: 'COORDINATE_CENTERPOINT' as SourceOfCountryEnum,
    REPORTEDVALUE: 'REPORTED_VALUE' as SourceOfCountryEnum,
    FINNISHMUNICIPALITY: 'FINNISH_MUNICIPALITY' as SourceOfCountryEnum,
    OLDFINNISHMUNICIPALITY: 'OLD_FINNISH_MUNICIPALITY' as SourceOfCountryEnum
  };
  export type SourceOfBiogeographicalProvinceEnum =
    'COORDINATES'
    | 'COORDINATE_CENTERPOINT'
    | 'REPORTED_VALUE'
    | 'FINNISH_MUNICIPALITY'
    | 'OLD_FINNISH_MUNICIPALITY';
  export const SourceOfBiogeographicalProvinceEnum = {
    COORDINATES: 'COORDINATES' as SourceOfBiogeographicalProvinceEnum,
    COORDINATECENTERPOINT: 'COORDINATE_CENTERPOINT' as SourceOfBiogeographicalProvinceEnum,
    REPORTEDVALUE: 'REPORTED_VALUE' as SourceOfBiogeographicalProvinceEnum,
    FINNISHMUNICIPALITY: 'FINNISH_MUNICIPALITY' as SourceOfBiogeographicalProvinceEnum,
    OLDFINNISHMUNICIPALITY: 'OLD_FINNISH_MUNICIPALITY' as SourceOfBiogeographicalProvinceEnum
  };
  export type SourceOfFinnishMunicipalityEnum =
    'COORDINATES'
    | 'COORDINATE_CENTERPOINT'
    | 'REPORTED_VALUE'
    | 'FINNISH_MUNICIPALITY'
    | 'OLD_FINNISH_MUNICIPALITY';
  export const SourceOfFinnishMunicipalityEnum = {
    COORDINATES: 'COORDINATES' as SourceOfFinnishMunicipalityEnum,
    COORDINATECENTERPOINT: 'COORDINATE_CENTERPOINT' as SourceOfFinnishMunicipalityEnum,
    REPORTEDVALUE: 'REPORTED_VALUE' as SourceOfFinnishMunicipalityEnum,
    FINNISHMUNICIPALITY: 'FINNISH_MUNICIPALITY' as SourceOfFinnishMunicipalityEnum,
    OLDFINNISHMUNICIPALITY: 'OLD_FINNISH_MUNICIPALITY' as SourceOfFinnishMunicipalityEnum
  };
}
