/* tslint:disable:max-line-length */
/**
 * API documentation
 * Access token is needed to use this API. To get a token, send a POST request with your email address to /api-users endpoint and one will be send to your. Each endpoint bellow has more information on how to use this API. If you have any questions you can contact us at helpdesk@laji.fi.  You can find more documentation [here](https://laji.fi/about/806).  ##Endpoints  Observations and collections * Warehouse - Observation Data Warehouse API * Collection - Collection metadata * Source - Information sources (IT systems) * Annotation - Quality control   Taxonomy * Taxa - Taxonomy API * InformalTaxonGroup - Informal taxon groups are used in taxa and warehouse endpoints * Publication - Scientific publications * Checklist - Mainly you only work with one checklits: the FinBIF master checklist. There are others.   Other master data * Metadata - Variable descriptions * Area - Countries, municipalities and biogeographical provinces of Finland, etc. * Person - Information about people.   Helpers * APIUser - Register as an API user * Autocomplete - For making an autocomplete filed for taxa, collections or persons (friends) * PersonToken - Information about an authorized person   Vihko observation system * Form - Form definition * Document - Document instance of a form * Image - Image of a document   Laji.fi portal * Feedback - Feedback form API * Information - CMS content of information pages * Logger - Error logging from user's browsers to FinBIF * News - News
 *
 * OpenAPI spec version: 0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Identification {
  /**
   * Write associated observation taxa names here, separated by a semicolon (;). E.g.: \\\"Betula pendula; Betula pubescens; Poaceae\\\". These will form their own units of the type observation.
   */
  associatedObservationTaxa?: string;
  /**
   * Author for the taxon
   */
  author?: string;
  /**
   * Name of the identifier (person) preferably in format \\\"lastname, firstname\\\"
   */
  det?: string;
  /**
   * Date or year when the identification was done, preferably in format \\\"d.m.Y\\\" or  \\\"Y\\\"
   */
  detDate?: string;
  detMethod?: Identification.DetMethodEnum;
  /**
   * Name of the identifier and date of identification in original format (e.g. from the label), errors and all
   */
  detVerbatim?: string;
  /**
   * Additional qualifier or specifier at genus level (e.g. aff., cf.)
   */
  genusQualifier?: string;
  identificationBasis?: Array<string>;
  identificationDate?: string;
  /**
   * Additional information on the identification, basis or such
   */
  identificationNotes?: string;
  /**
   * Author for the taxon below species level/infra epithet
   */
  infraAuthor?: string;
  /**
   * Taxon name for the epithet below species level
   */
  infraEpithet?: string;
  /**
   * Taxonomic level of the epithet below species level
   */
  infraRank?: Identification.InfraRankEnum;
  /**
   * Pathovars, serovars and other infrasubspecific subdivisions of microbes.
   */
  infrasubspecificSubdivision?: string;
  isTaxonGroup?: boolean;
  /**
   * This can be used to select one of the identifications as 'recommended', which is the used as default when displaying information about the specimen.
   */
  preferredIdentification?: string;
  /**
   * PUBLIC: all data can be published; PROTECTED: exact locality is hidden (100*100km square); PRIVATE: most of the data is hidden. Empty value means same as public.
   */
  publicityRestrictions?: Identification.PublicityRestrictionsEnum;
  /**
   * Publication reference for the taxon concept, that was used in identification
   */
  sec?: string;
  sortOrder?: number;
  /**
   * Additional qualifier at species level (e.g. aff., cf., sp. n., coll.)
   */
  speciesQualifier?: string;
  /**
   * Taxon name
   */
  taxon?: string;
  /**
   * ID for the taxon if has some other than an MX code
   */
  taxonID?: string;
  /**
   * Taxonomic level for the identification
   */
  taxonRank?: Identification.TaxonRankEnum;
  taxonSpecifier?: string;
  /**
   * QName for MX.taxon
   */
  taxonURI?: string;
  /**
   * Taxon name in original format (e.g. from the label), errors and all
   */
  taxonVerbatim?: string;
}

export namespace Identification {
  export type DetMethodEnum = 'MY.detMethodFreshSample' | 'MY.detMethodMicroscopy' | 'MY.detMethodPhoto';
  export const DetMethodEnum = {
    DetMethodFreshSample: 'MY.detMethodFreshSample' as DetMethodEnum,
    DetMethodMicroscopy: 'MY.detMethodMicroscopy' as DetMethodEnum,
    DetMethodPhoto: 'MY.detMethodPhoto' as DetMethodEnum
  };
  export type InfraRankEnum =
    'MY.infraRankSsp'
    | 'MY.infraRankVar'
    | 'MY.infraRankBeta'
    | 'MY.infraRankB'
    | 'MY.infraRankForma'
    | 'MY.infraRankHybrid'
    | 'MY.infraRankAnamorph'
    | 'MY.infraRankAggregate'
    | 'MY.infraRankAberration'
    | 'MY.infraRankCultivar'
    | 'MY.infraRankMorpha'
    | 'MY.infraRankUnknown'
    | 'MY.infraRankNothosubspecies'
    | 'MY.infraRankCultivarGroup';
  export const InfraRankEnum = {
    InfraRankSsp: 'MY.infraRankSsp' as InfraRankEnum,
    InfraRankVar: 'MY.infraRankVar' as InfraRankEnum,
    InfraRankBeta: 'MY.infraRankBeta' as InfraRankEnum,
    InfraRankB: 'MY.infraRankB' as InfraRankEnum,
    InfraRankForma: 'MY.infraRankForma' as InfraRankEnum,
    InfraRankHybrid: 'MY.infraRankHybrid' as InfraRankEnum,
    InfraRankAnamorph: 'MY.infraRankAnamorph' as InfraRankEnum,
    InfraRankAggregate: 'MY.infraRankAggregate' as InfraRankEnum,
    InfraRankAberration: 'MY.infraRankAberration' as InfraRankEnum,
    InfraRankCultivar: 'MY.infraRankCultivar' as InfraRankEnum,
    InfraRankMorpha: 'MY.infraRankMorpha' as InfraRankEnum,
    InfraRankUnknown: 'MY.infraRankUnknown' as InfraRankEnum,
    InfraRankNothosubspecies: 'MY.infraRankNothosubspecies' as InfraRankEnum,
    InfraRankCultivarGroup: 'MY.infraRankCultivarGroup' as InfraRankEnum
  };
  export type PublicityRestrictionsEnum =
    'MZ.publicityRestrictionsPublic'
    | 'MZ.publicityRestrictionsProtected'
    | 'MZ.publicityRestrictionsPrivate';
  export const PublicityRestrictionsEnum = {
    PublicityRestrictionsPublic: 'MZ.publicityRestrictionsPublic' as PublicityRestrictionsEnum,
    PublicityRestrictionsProtected: 'MZ.publicityRestrictionsProtected' as PublicityRestrictionsEnum,
    PublicityRestrictionsPrivate: 'MZ.publicityRestrictionsPrivate' as PublicityRestrictionsEnum
  };
  export type TaxonRankEnum =
    'MX.superdomain'
    | 'MX.domain'
    | 'MX.kingdom'
    | 'MX.subkingdom'
    | 'MX.infrakingdom'
    | 'MX.superphylum'
    | 'MX.phylum'
    | 'MX.subphylum'
    | 'MX.infraphylum'
    | 'MX.superdivision'
    | 'MX.division'
    | 'MX.subdivision'
    | 'MX.infradivision'
    | 'MX.superclass'
    | 'MX.class'
    | 'MX.subclass'
    | 'MX.infraclass'
    | 'MX.parvclass'
    | 'MX.superorder'
    | 'MX.order'
    | 'MX.suborder'
    | 'MX.infraorder'
    | 'MX.parvorder'
    | 'MX.superfamily'
    | 'MX.family'
    | 'MX.subfamily'
    | 'MX.tribe'
    | 'MX.subtribe'
    | 'MX.supergenus'
    | 'MX.genus'
    | 'MX.nothogenus'
    | 'MX.subgenus'
    | 'MX.section'
    | 'MX.subsection'
    | 'MX.series'
    | 'MX.subseries'
    | 'MX.infragenericTaxon'
    | 'MX.aggregate'
    | 'MX.species'
    | 'MX.nothospecies'
    | 'MX.infraspecificTaxon'
    | 'MX.subspecificAggregate'
    | 'MX.subspecies'
    | 'MX.nothosubspecies'
    | 'MX.variety'
    | 'MX.subvariety'
    | 'MX.form'
    | 'MX.subform'
    | 'MX.hybrid'
    | 'MX.anamorph'
    | 'MX.ecotype'
    | 'MX.populationGroup'
    | 'MX.intergenericHybrid'
    | 'MX.infragenericHybrid'
    | 'MX.cultivar'
    | 'MX.group'
    | 'MX.speciesAggregate';
  export const TaxonRankEnum = {
    Superdomain: 'MX.superdomain' as TaxonRankEnum,
    Domain: 'MX.domain' as TaxonRankEnum,
    Kingdom: 'MX.kingdom' as TaxonRankEnum,
    Subkingdom: 'MX.subkingdom' as TaxonRankEnum,
    Infrakingdom: 'MX.infrakingdom' as TaxonRankEnum,
    Superphylum: 'MX.superphylum' as TaxonRankEnum,
    Phylum: 'MX.phylum' as TaxonRankEnum,
    Subphylum: 'MX.subphylum' as TaxonRankEnum,
    Infraphylum: 'MX.infraphylum' as TaxonRankEnum,
    Superdivision: 'MX.superdivision' as TaxonRankEnum,
    Division: 'MX.division' as TaxonRankEnum,
    Subdivision: 'MX.subdivision' as TaxonRankEnum,
    Infradivision: 'MX.infradivision' as TaxonRankEnum,
    Superclass: 'MX.superclass' as TaxonRankEnum,
    Class: 'MX.class' as TaxonRankEnum,
    Subclass: 'MX.subclass' as TaxonRankEnum,
    Infraclass: 'MX.infraclass' as TaxonRankEnum,
    Parvclass: 'MX.parvclass' as TaxonRankEnum,
    Superorder: 'MX.superorder' as TaxonRankEnum,
    Order: 'MX.order' as TaxonRankEnum,
    Suborder: 'MX.suborder' as TaxonRankEnum,
    Infraorder: 'MX.infraorder' as TaxonRankEnum,
    Parvorder: 'MX.parvorder' as TaxonRankEnum,
    Superfamily: 'MX.superfamily' as TaxonRankEnum,
    Family: 'MX.family' as TaxonRankEnum,
    Subfamily: 'MX.subfamily' as TaxonRankEnum,
    Tribe: 'MX.tribe' as TaxonRankEnum,
    Subtribe: 'MX.subtribe' as TaxonRankEnum,
    Supergenus: 'MX.supergenus' as TaxonRankEnum,
    Genus: 'MX.genus' as TaxonRankEnum,
    Nothogenus: 'MX.nothogenus' as TaxonRankEnum,
    Subgenus: 'MX.subgenus' as TaxonRankEnum,
    Section: 'MX.section' as TaxonRankEnum,
    Subsection: 'MX.subsection' as TaxonRankEnum,
    Series: 'MX.series' as TaxonRankEnum,
    Subseries: 'MX.subseries' as TaxonRankEnum,
    InfragenericTaxon: 'MX.infragenericTaxon' as TaxonRankEnum,
    Aggregate: 'MX.aggregate' as TaxonRankEnum,
    Species: 'MX.species' as TaxonRankEnum,
    Nothospecies: 'MX.nothospecies' as TaxonRankEnum,
    InfraspecificTaxon: 'MX.infraspecificTaxon' as TaxonRankEnum,
    SubspecificAggregate: 'MX.subspecificAggregate' as TaxonRankEnum,
    Subspecies: 'MX.subspecies' as TaxonRankEnum,
    Nothosubspecies: 'MX.nothosubspecies' as TaxonRankEnum,
    Variety: 'MX.variety' as TaxonRankEnum,
    Subvariety: 'MX.subvariety' as TaxonRankEnum,
    Form: 'MX.form' as TaxonRankEnum,
    Subform: 'MX.subform' as TaxonRankEnum,
    Hybrid: 'MX.hybrid' as TaxonRankEnum,
    Anamorph: 'MX.anamorph' as TaxonRankEnum,
    Ecotype: 'MX.ecotype' as TaxonRankEnum,
    PopulationGroup: 'MX.populationGroup' as TaxonRankEnum,
    IntergenericHybrid: 'MX.intergenericHybrid' as TaxonRankEnum,
    InfragenericHybrid: 'MX.infragenericHybrid' as TaxonRankEnum,
    Cultivar: 'MX.cultivar' as TaxonRankEnum,
    Group: 'MX.group' as TaxonRankEnum,
    SpeciesAggregate: 'MX.speciesAggregate' as TaxonRankEnum
  };
}
