/**
 * OpenAPI spec version: 0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface GatheringEvent {

    dateBegin?: string;

    dateEnd?: string;

    /**
     * Unique ID for the object. This will be automatically generated.
     */
    id?: string;

    leg?: Array<string>;

    legPublic?: boolean;

    /**
     * Alkuperäislähteen käyttäjätunnus
     */
    legUserID?: Array<string>;

    namedPlaceNotes?: string;

    routeDirectionAdhered?: boolean;

    startDistanceFromNECorner?: string;

    startPointDeviation?: number;

    timeEnd?: string;

    timeStart?: string;

}
